Repository lima-vm/lima, pull requests merged in 2021-09, with the labels that each got.

#197 Make sure user provisioning scripts can be executed
  pkg/cidata/cidata.TEMPLATE.d/boot.sh
Labels: bug

#195 Allow users to define custom environment variables to be loaded on VM start
  pkg/cidata/cidata.TEMPLATE.d/lima.env
  pkg/cidata/cidata.go
  pkg/cidata/template.go
  pkg/limayaml/default.yaml
  pkg/limayaml/limayaml.go
Labels: enhancement

#199 Pass DNS addresses from en0 interface to guest instance
  pkg/cidata/cidata.TEMPLATE.d/network-config
  pkg/cidata/cidata.go
  pkg/cidata/template.go
  pkg/osutil/dns_darwin.go
  pkg/osutil/dns_others.go
  pkg/osutil/osutil_others.go
  pkg/sysprof/network_darwin.go
  pkg/sysprof/sysprof_darwin.go
Labels: enhancement, status/merge-on-green

#203 go.mod: downgrade pkg/sftp to v1.12.0 (fix `nerdctl run -v` hang up)
  go.mod
  go.sum
  hack/test-example.sh
Labels: priority/high

#212 Fix brew install issue with Github actions
  .github/workflows/test.yml
Labels: bug, area/ci

#214 Use "lima" username if the local user is not a valid Linux name
  cmd/limactl/copy.go
  pkg/cidata/cidata.go
  pkg/limayaml/validate.go
  pkg/osutil/user.go
  pkg/sshutil/sshutil.go
Labels: enhancement

#218 Provide explicit DNS override
  pkg/cidata/cidata.go
  pkg/limayaml/default.yaml
  pkg/limayaml/limayaml.go
Labels: enhancement

#219 Ignore public keys that are not in ssh format
  examples/alpine.yaml
  pkg/cidata/cidata.TEMPLATE.d/user-data
  pkg/sshutil/sshutil.go
Labels: bug

#210 examples: add {docker,podman,singularity}.yaml
  README.md
  examples/README.md
  examples/docker.yaml
  examples/podman.yaml
  examples/singularity.yaml
Labels: documentation

#217 Add manage_resolv_conf to cloud-init
  pkg/cidata/cidata.TEMPLATE.d/user-data
  pkg/cidata/cidata.go
  pkg/cidata/template.go
  pkg/qemu/qemuconst/qemuconst.go
Labels: enhancement

#227 Bump Alpine image to support /etc/resolv.conf updates
  examples/alpine.yaml
Labels: enhancement

#215 README.md: update ARM installation steps (`brew install simnalamburt/x/qemu-hvf`)
  README.md
Labels: documentation, platform/ARM

#241 Use numeric uid/gid with chown
  pkg/cidata/cidata.TEMPLATE.d/boot/25-guestagent-base.sh
Labels: bug

#243 Map usernames not allowed by useradd to the fallbackUser "lima"
  pkg/osutil/user.go
Labels: bug

#208 Provide an easier binary manual installation example command
  README.md
Labels: documentation

#247 Switch sshfs mount options `-o allow_root` to `-o allow_other`
  pkg/hostagent/mount.go
  pkg/limayaml/default.yaml
Labels: impact/changelog

#225 README.md: add adopters list (Rancher Desktop, Colima)
  README.md
Labels: documentation

#249 examples: update {archlinux,debian}.yaml
  examples/archlinux.yaml
  examples/debian.yaml
Labels: guest/archlinux, guest/debian

#248 nerdctl: update to v0.11.2
  pkg/cidata/cidata.go
Labels: component/nerdctl, impact/changelog

#234 make nerdctl.lima completion works
  cmd/lima-guestagent/daemon_linux.go
  cmd/lima-guestagent/install_systemd_linux.go
  cmd/lima-guestagent/main_linux.go
  cmd/limactl/completion.go
  cmd/limactl/copy.go
  cmd/limactl/delete.go
  cmd/limactl/hostagent.go
  cmd/limactl/list.go
  cmd/limactl/main.go
  cmd/limactl/prune.go
  cmd/limactl/shell.go
  cmd/limactl/start.go
  cmd/limactl/stop.go
  cmd/limactl/validate.go
  go.mod
  go.sum
Labels: impact/changelog

#242 Enable sudo nerdctl run to expose ports to localhost
  cmd/lima-guestagent/daemon_linux.go
  cmd/lima-guestagent/install_systemd_linux.go
  cmd/lima-guestagent/lima-guestagent.TEMPLATE.service
  cmd/lima-guestagent/main_linux.go
  docs/internal.md
  pkg/cidata/cidata.TEMPLATE.d/boot/25-guestagent-base.sh
  pkg/guestagent/guestagent_linux.go
  pkg/guestagent/iptables/iptables.go
  pkg/guestagent/iptables/iptables_test.go
  pkg/hostagent/hostagent.go
  pkg/hostagent/requirements.go
Labels: bug, impact/changelog

#245 Add `/opt/vde/bin/vde_vmnet` and prerequites to lima-and-qemu tarball
  hack/lima-and-qemu.pl
Labels: enhancement, component/vde_vmnet

#239 Implement vde_vmnet management
  .github/workflows/test.yml
  cmd/limactl/delete.go
  cmd/limactl/main.go
  cmd/limactl/start.go
  cmd/limactl/stop.go
  cmd/limactl/sudoers.go
  docs/network.md
  examples/vmnet.yaml
  pkg/cidata/cidata.TEMPLATE.d/network-config
  pkg/cidata/cidata.go
  pkg/cidata/template.go
  pkg/limayaml/default.yaml
  pkg/limayaml/defaults.go
  pkg/limayaml/limayaml.go
  pkg/limayaml/validate.go
  pkg/networks/commands.go
  pkg/networks/commands_test.go
  pkg/networks/config.go
  pkg/networks/networks.go
  pkg/networks/networks.yaml
  pkg/networks/reconcile/reconcile.go
  pkg/networks/sudoers.go
  pkg/networks/validate.go
  pkg/osutil/user.go
  pkg/qemu/const/const.go
  pkg/qemu/qemu.go
  pkg/sshutil/sshutil.go
  pkg/store/dirnames/dirnames.go
  pkg/store/filenames/filenames.go
  pkg/store/instance.go
  pkg/store/store.go
Labels: enhancement, component/vde_vmnet, impact/changelog

#262 Don't use dockerhub to avoid hitting rate limits in CI
  hack/test-example.sh
  pkg/networks/networks.go
Labels: area/ci

#272 Remove deprecation warning in debug
  pkg/qemu/qemu.go
Labels: enhancement

#266 Setup proxy environment variables from system settings
  pkg/cidata/cidata.go
  pkg/cidata/template.go
  pkg/limayaml/default.yaml
  pkg/limayaml/limayaml.go
  pkg/osutil/dns_darwin.go
  pkg/osutil/dns_others.go
  pkg/sysprof/network_darwin.go
Labels: enhancement
