Repository lima-vm/lima, pull requests merged in 2021-12, with the labels that each got.

#447 examples: update README.md, {archlinux, debian}.yaml
  examples/README.md
  examples/archlinux.yaml
  examples/debian.yaml
Labels: guest/archlinux, guest/debian

#433 Change the default prompt color from green to lime
  docs/internal.md
  pkg/cidata/cidata.TEMPLATE.d/boot/08-shell-prompt.sh
  pkg/cidata/cidata.TEMPLATE.d/lima.env
Labels: enhancement

#448 examples: centos.yaml (8.4) -> rocky.yaml (8.5)
  README.md
  examples/README.md
  examples/rocky.yaml
Labels: guest/el8

#464 CI: update vde_vmnet to v0.5.2
  .github/workflows/test.yml
Labels: area/ci

#465 Delete closed issue link on help wanted section
  README.md
Labels: documentation

#484 README.md: ARM hosts no longer need QEMU to be patched
  README.md
Labels: documentation

#494 Fix #471: Improve x86_64 emulation on arm64 platform
  pkg/qemu/qemu.go
Labels: platform/ARM

#495 Enabled symbolic link following in mounts
  pkg/hostagent/mount.go
  pkg/limayaml/default.yaml
  pkg/limayaml/defaults.go
  pkg/limayaml/defaults_test.go
  pkg/limayaml/limayaml.go
Labels: component/sshfs
