Repository lima-vm/lima, pull requests merged in 2021-11, with the labels that each got.

#372 examples/{fedora,singularity}.yaml: update Fedora to 35
  examples/fedora.yaml
  examples/singularity.yaml
Labels: guest/fedora

#373 Bump Alpine ISO to v0.2.0 - includes aarch64 version
  examples/alpine.yaml
Labels: guest/alpine

#379 nerdctl 0.13 ; add `./docs-multi-arch.md`
  README.md
  docs/multi-arch.md
  pkg/limayaml/defaults.go
Labels: component/nerdctl

#415 docs: show --tty usage
  README.md
Labels: documentation

#426 nerdctl: update to v0.14.0; install bash completion; update {archlinux,debian}.yaml
  .github/workflows/test.yml
  examples/archlinux.yaml
  examples/debian.yaml
  pkg/cidata/cidata.TEMPLATE.d/boot/40-install-containerd.sh
  pkg/limayaml/defaults.go
Labels: component/nerdctl

#437 Bump Alpine from 3.13.5 → 3.14.3
  examples/alpine.yaml
Labels: guest/alpine

#438 limactl --list-fields should list them in sort order
  cmd/limactl/list.go
Labels: enhancement
