Repository lima-vm/lima, pull requests merged in 2021-06, with the labels that each got.

#91 Add openSUSE example config (using JeOS image for OpenStack).
  .github/workflows/test.yml
  examples/opensuse.yaml
  pkg/cidata/cidata.TEMPLATE.d/boot/30-install-packages.sh
  pkg/cidata/cidata.TEMPLATE.d/boot/40-install-containerd.sh
Labels: enhancement

#92 Add copy/cp/scp command
  cmd/limactl/copy.go
  cmd/limactl/main.go
  hack/test-example.sh
  pkg/sshutil/sshutil.go
Labels: enhancement

#98 README updates: add openSUSE, remove outdated FAQs
  README.md
Labels: documentation

#100 Move /etc/ssh to persistent data-volume
  pkg/cidata/cidata.TEMPLATE.d/boot/05-persistent-data-volume.sh
Labels: enhancement, guest/alpine

#99 Don't reload sshd service if it hasn't started yet
  pkg/cidata/cidata.TEMPLATE.d/boot/10-alpine-prep.sh
Labels: bug, guest/alpine

#95 CI: add .cirrus.yml
  .cirrus.yml
  .github/workflows/test.yml
Labels: area/ci
