Repository lima-vm/lima, pull requests merged in 2021-08, with the labels that each got.

#143 Persist all of /etc on the data volume
  pkg/cidata/cidata.TEMPLATE.d/boot/05-persistent-data-volume.sh
Labels: guest/alpine

#149 Verify that the process specified in a PID file is still running
  pkg/store/instance.go
Labels: bug

#166 remove direct dependency on github.com/pkg/errors
  cmd/lima-guestagent/daemon_linux.go
  cmd/limactl/copy.go
  cmd/limactl/delete.go
  cmd/limactl/hostagent.go
  cmd/limactl/list.go
  cmd/limactl/shell.go
  cmd/limactl/start.go
  cmd/limactl/stop.go
  cmd/limactl/validate.go
  go.mod
  pkg/cidata/cidata.go
  pkg/cidata/template.go
  pkg/downloader/downloader.go
  pkg/guestagent/procnettcp/procnettcp.go
  pkg/guestagent/procnettcp/procnettcp_linux.go
  pkg/hostagent/hostagent.go
  pkg/hostagent/mount.go
  pkg/hostagent/port.go
  pkg/hostagent/requirements.go
  pkg/httpclientutil/httpclientutil.go
  pkg/limayaml/validate.go
  pkg/localpathutil/localpathutil.go
  pkg/lockutil/lockutil.go
  pkg/qemu/qemu.go
  pkg/sshutil/sshutil.go
  pkg/start/start.go
  pkg/store/store.go
Labels: kind/refactoring

#174 qemu-img 6.1.0 no longer supports using -b without -F
  pkg/qemu/qemu.go
Labels: priority/high

#180 Add openSUSE location for UEFI firmware
  pkg/qemu/qemu.go
Labels: enhancement
