Repository lima-vm/lima, pull requests merged in 2022-01, with the labels that each got.

#509 Don't include default settings in example configs
  examples/alpine.yaml
  examples/archlinux.yaml
  examples/debian.yaml
  examples/docker.yaml
  examples/fedora.yaml
  examples/opensuse.yaml
  examples/podman.yaml
  examples/rocky.yaml
  examples/singularity.yaml
  examples/ubuntu.yaml
  examples/vmnet.yaml
  pkg/limayaml/default.yaml
Labels: status/merge-on-green

#520 examples/debian.yaml: bump debian version
  examples/debian.yaml
Labels: guest/debian

#538 Don't cache sshfs directory, fixes abiosoft/colima#99
  pkg/hostagent/mount.go
Labels: component/sshfs, impact/changelog

#564 Make sshfs caching configurable
  pkg/hostagent/mount.go
  pkg/limayaml/default.yaml
  pkg/limayaml/defaults.go
  pkg/limayaml/defaults_test.go
  pkg/limayaml/limayaml.go
Labels: enhancement, component/sshfs

#566 dont upgrade pkg when install sshf
  pkg/cidata/cidata.TEMPLATE.d/boot/30-install-packages.sh
Labels: guest/archlinux, component/sshfs

#565 README.md: clarify that Lima is similar to WSL2 but not similar to WSL1
  README.md
Labels: documentation

#580 examples: update {archlinux,debian}.yaml
  examples/archlinux.yaml
  examples/debian.yaml
Labels: guest/archlinux, guest/debian

#583 Add SECURITY.md (and MAINTAINERS.md)
  MAINTAINERS.md
  SECURITY.md
Labels: documentation, area/project

#582 Add the Slack link
  .github/ISSUE_TEMPLATE/config.yml
  README.md
Labels: documentation, area/project

#593 Fix .github/ISSUE_TEMPLATE
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: area/project

#595 start.ShowMessage: remove the logrus INFO header, for ease of copypasting
  examples/docker.yaml
  pkg/start/start.go
Labels: enhancement

#599 Spelling
  cmd/limactl/start.go
  docs/multi-arch.md
  hack/test-example.sh
  pkg/limayaml/default.yaml
  pkg/limayaml/validate.go
  pkg/sshutil/sshutil.go
Labels: documentation

#572 Add edit command
  README.md
  cmd/limactl/edit.go
  cmd/limactl/main.go
  cmd/limactl/start.go
Labels: enhancement, impact/changelog

#613 examples: Bring Ubuntu LTS (20.04 focal) to Lima
  examples/README.md
  examples/ubuntu-lts.yaml
Labels: guest/ubuntu
