Repository lima-vm/lima, pull requests merged in 2022-03, with the labels that each got.

#696 Use system_profiler fallback if hostname address cannot be determined
  hack/test-port-forwarding.pl
Labels: area/ci

#695 nerdctl: use fuse-overlayfs only when kernel < 5.13
  docs/internal.md
  pkg/cidata/cidata.TEMPLATE.d/boot.sh
  pkg/cidata/cidata.TEMPLATE.d/boot/20-rootless-base.sh
  pkg/cidata/cidata.TEMPLATE.d/boot/40-install-containerd.sh
  pkg/cidata/cidata.TEMPLATE.d/util/compare_version.sh
Labels: enhancement, component/nerdctl, impact/changelog

#694 cidata: automatically upgrade existing containerd/nerdctl ; nerdctl: update to v0.17.1
  pkg/cidata/cidata.TEMPLATE.d/boot/40-install-containerd.sh
  pkg/limayaml/defaults.go
Labels: enhancement, component/nerdctl, impact/changelog

#700 Add support for oracle linux 8.
  examples/README.md
  examples/oraclelinux.yaml
  pkg/cidata/cidata.TEMPLATE.d/boot/30-install-packages.sh
Labels: guest/el8

#704 aarch64: remove outdated hint
  pkg/qemu/qemu.go
Labels: platform/ARM, component/qemu

#705 README.md: nits; sync README.ja.md
  README.ja.md
  README.md
Labels: documentation

#674 limactl start: support `limactl start template://TEMPLATE`
  Makefile
  README.md
  cmd/limactl/edit.go
  cmd/limactl/info.go
  cmd/limactl/start.go
  examples/README.md
  examples/default.yaml
  hack/test-port-forwarding.pl
  pkg/cidata/cidata.go
  pkg/limayaml/default.yaml
  pkg/limayaml/template.go
  pkg/limayaml/template_test.go
  pkg/usrlocalsharelima/usrlocalsharelima.go
Labels: enhancement, impact/changelog

#707 examples/default.yaml: clarify YAML default vs builtin default
  examples/default.yaml
Labels: documentation

#706 cidata: Install packages at once
  pkg/cidata/cidata.TEMPLATE.d/boot/30-install-packages.sh
Labels: kind/refactoring

#701 docs: add sequence diagram
  Makefile
  docs/internal.md
  docs/lima-sequence-diagram.png
  docs/lima-sequence-diagram.puml
Labels: documentation

#710 CI: reduce GHA parallelism to avoid limit
  .github/workflows/test.yml
Labels: area/ci

#708 CI: add upgrade test
  .github/workflows/test.yml
  .shellcheckrc
  hack/common.inc.sh
  hack/test-example.sh
  hack/test-mount-home.sh
  hack/test-upgrade.sh
Labels: area/ci

#703 aarch64: unset highmem=off for QEMU >= 7.0
  pkg/qemu/qemu.go
Labels: platform/ARM, component/qemu

#717 Ubuntu: skip kernel 5.13.0-35.40 (5.4.0-103.117 for 20.04 LTS)
  examples/buildkit.yaml
  examples/default.yaml
  examples/docker.yaml
  examples/faasd.yaml
  examples/k3s.yaml
  examples/k8s.yaml
  examples/nomad.yaml
  examples/podman.yaml
  examples/ubuntu-lts.yaml
  examples/ubuntu.yaml
  examples/vmnet.yaml
  pkg/start/start.go
Labels: guest/ubuntu

#721 Add lima logo image
  docs/images/lima-logo-01.svg
Labels: area/project

#725 README.md: add logo
  README.md
  docs/images/lima-logo-01.svg
  docs/images/lima-sequence-diagram.png
  docs/images/lima-sequence-diagram.puml
  docs/internal.md
Labels: documentation

#732 Fix curl url
  README.md
Labels: documentation

#733 Add ovmf candidates for archlinux
  pkg/qemu/qemu.go
Labels: host/Linux, component/qemu

#738 Hostresolver: Treat AAAA queries as A queries when IPv6 is disabled
  pkg/hostagent/dns/dns.go
Labels: bug

#739 CI: use Go 1.18
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: area/ci

#750 Arch Linux aarch64 image
  examples/archlinux.yaml
Labels: platform/ARM, guest/archlinux

#753 CI: use vde_vmnet v0.6.0
  .github/workflows/test.yml
Labels: area/ci, component/vde_vmnet

#756 nerdctl: update to v0.18.0; configure BuildKit with containerd worker
  pkg/cidata/cidata.TEMPLATE.d/boot/40-install-containerd.sh
  pkg/limayaml/defaults.go
Labels: component/nerdctl, impact/changelog
