Repository lima-vm/lima, pull requests merged in 2022-04, with the labels that each got.

#726 Add virtfs/9p mounts, instead of sshocker/sshfs
  .github/workflows/test.yml
  README.md
  docs/internal.md
  examples/README.md
  examples/default.yaml
  examples/experimental-9p.yaml
  pkg/cidata/cidata.TEMPLATE.d/boot/25-guestagent-base.sh
  pkg/cidata/cidata.TEMPLATE.d/boot/30-install-packages.sh
  pkg/cidata/cidata.TEMPLATE.d/lima.env
  pkg/cidata/cidata.TEMPLATE.d/user-data
  pkg/cidata/cidata.go
  pkg/cidata/template.go
  pkg/cidata/template_test.go
  pkg/hostagent/hostagent.go
  pkg/hostagent/requirements.go
  pkg/limayaml/defaults.go
  pkg/limayaml/defaults_test.go
  pkg/limayaml/limayaml.go
  pkg/limayaml/validate.go
  pkg/qemu/qemu.go
Labels: enhancement, impact/changelog, component/qemu

#784 examples: mv experimental-9p.yaml -> experimental/9p.yaml
  .github/workflows/test.yml
  examples/README.md
  examples/experimental/9p.yaml
Labels: component/qemu/9p

#787 9p: use `fscache` by default for RO mounts
  examples/default.yaml
  examples/experimental/9p.yaml
  pkg/limayaml/defaults.go
  pkg/limayaml/defaults_test.go
Labels: area/performance, component/qemu/9p

#797 CI: fix 'fatal: unsafe repository ('/Users/runner/work/lima/lima/vde_vmnet' is owned by someone else)'
  .github/workflows/test.yml
Labels: area/ci

#798 CI: update actions
  .github/dependabot.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: area/ci

#800 CI: upload go-mod-vendor.tar.gz as a backup
  .github/workflows/release.yml
  .github/workflows/test.yml
  Makefile
Labels: area/ci

#804 sshfs: support setting `sftpDriver: "openssh-sftp-server"`
  README.md
  docs/mount.md
  examples/default.yaml
  go.mod
  go.sum
  pkg/hostagent/mount.go
  pkg/limayaml/defaults.go
  pkg/limayaml/defaults_test.go
  pkg/limayaml/limayaml.go
Labels: component/sshfs

#806 docs/mount.md: clarify required Lima version
  docs/mount.md
Labels: documentation

#796 [Test wanted] qemu: adjust the memory size for workarounding M1 panic
  pkg/qemu/qemu.go
Labels: help wanted, platform/ARM

#811 examples: update Ubuntu (22.04), Debian, Arch; nerdctl: update to v0.19.0
  README.md
  docs/multi-arch.md
  examples/alpine.yaml
  examples/archlinux.yaml
  examples/buildkit.yaml
  examples/debian.yaml
  examples/default.yaml
  examples/docker.yaml
  examples/experimental/9p.yaml
  examples/faasd.yaml
  examples/k3s.yaml
  examples/k8s.yaml
  examples/nomad.yaml
  examples/podman.yaml
  examples/ubuntu-lts.yaml
  examples/ubuntu.yaml
  examples/vmnet.yaml
  pkg/limayaml/defaults.go
Labels: guest/archlinux, guest/debian, guest/ubuntu, component/nerdctl

#816 README.ja.md: sync (2022-Apr-25)
  README.ja.md
  README.md
Labels: documentation
