Repository lima-vm/lima, pull requests merged in 2022-11, with the labels that each got.

#1142 qemu: do not use `-device ramfb` for RISC-V
  pkg/qemu/qemu.go
Labels: component/qemu

#1065 Add `disk` command and allows multiple additional disks
  .github/workflows/test.yml
  README.md
  cmd/limactl/disk.go
  cmd/limactl/main.go
  cmd/limactl/stop.go
  docs/internal.md
  examples/default.yaml
  examples/disk.yaml
  hack/test-example.sh
  pkg/cidata/cidata.TEMPLATE.d/boot.sh
  pkg/cidata/cidata.TEMPLATE.d/boot/04-persistent-data-volume.sh
  pkg/cidata/cidata.TEMPLATE.d/boot/05-lima-disks.sh
  pkg/cidata/cidata.TEMPLATE.d/boot/07-etc-environment.sh
  pkg/cidata/cidata.TEMPLATE.d/lima.env
  pkg/cidata/cidata.go
  pkg/cidata/template.go
  pkg/hostagent/hostagent.go
  pkg/limayaml/defaults.go
  pkg/limayaml/defaults_test.go
  pkg/limayaml/limayaml.go
  pkg/qemu/imgutil/imgutil.go
  pkg/qemu/qemu.go
  pkg/store/dirnames/dirnames.go
  pkg/store/disk.go
  pkg/store/filenames/filenames.go
  pkg/store/instance.go
  pkg/store/store.go
Labels: enhancement, impact/changelog

#1147 Support for Virtualization.Framework for macOS 13
  Makefile
  cmd/limactl/stop.go
  docs/internal.md
  docs/mount.md
  docs/vmtype.md
  examples/experimental/vz.yaml
  go.mod
  go.sum
  pkg/cidata/cidata.TEMPLATE.d/boot/25-guestagent-base.sh
  pkg/cidata/cidata.TEMPLATE.d/network-config
  pkg/cidata/cidata.TEMPLATE.d/user-data
  pkg/cidata/cidata.go
  pkg/cidata/cidata_test.go
  pkg/driver/driver.go
  pkg/driverutil/instance.go
  pkg/fileutils/download.go
  pkg/hostagent/hostagent.go
  pkg/limayaml/defaults.go
  pkg/limayaml/defaults_test.go
  pkg/limayaml/limayaml.go
  pkg/limayaml/validate.go
  pkg/networks/const.go
  pkg/networks/gvisor.go
  pkg/qemu/imgutil/imgutil.go
  pkg/qemu/qemu.go
  pkg/qemu/qemu_driver.go
  pkg/start/start.go
  pkg/store/filenames/filenames.go
  pkg/store/instance.go
  pkg/vz/disk.go
  pkg/vz/vm_darwin.go
  pkg/vz/vz_driver_darwin.go
  pkg/vz/vz_driver_others.go
  vz.entitlements
Labels: impact/changelog, component/vz

#1159 templates: update Fedora to 37
  examples/apptainer-rootful.yaml
  examples/apptainer.yaml
  examples/fedora.yaml
  examples/podman-rootful.yaml
  examples/podman.yaml
Labels: guest/fedora, podman

#1163 vz: update docs
  docs/mount.md
  docs/vmtype.md
  examples/default.yaml
  examples/experimental/vz.yaml
Labels: documentation, component/vz

#1164 vz: fix readonly mounts
  pkg/cidata/cidata.go
Labels: component/vz

#1170 fix alpine data-volume issue
  pkg/vz/vm_darwin.go
Labels: guest/alpine, component/vz

#1168 templates: alpine: remove legacyBIOS=true
  examples/alpine.yaml
Labels: guest/alpine

#1174 Bump k8s flannel version from 0.20.0 to 0.20.1
  examples/k8s.yaml
Labels: kubernetes

#1173 fix host network resolver issue with alpine
  pkg/networks/gvisor.go
Labels: component/vz

#1171 support for driver specific pid files
  cmd/limactl/stop.go
  docs/internal.md
  pkg/qemu/qemu.go
  pkg/qemu/qemu_driver.go
  pkg/store/filenames/filenames.go
  pkg/store/instance.go
  pkg/vz/vm_darwin.go
Labels: component/vz

#1175 Fix compilation on macOS 10.15
  .github/workflows/test.yml
  Makefile
  pkg/vz/vm_darwin.go
  pkg/vz/vz_driver_darwin.go
  pkg/vz/vz_driver_others.go
Labels: component/vz

#1188 CI: remove catalina (macOS 10.15)
  .github/workflows/test.yml
Labels: area/ci

#1186 pkg/limayaml: remove deprecated `network` and `useHostResolver`
  pkg/limayaml/defaults.go
  pkg/limayaml/defaults_test.go
  pkg/limayaml/limayaml.go
  pkg/limayaml/validate.go
Labels: impact/changelog

#1191 CI: update socket_vmnet (1.0.0)
  .github/workflows/test.yml
Labels: area/ci, component/vmnet

#1192 CI: update socket_vmnet (1.1.0)
  .github/workflows/test.yml
Labels: area/ci, component/vmnet

#1155 Support Rosetta with VZ driver
  examples/experimental/vz.yaml
  pkg/cidata/cidata.TEMPLATE.d/boot/05-rosetta-volume.sh
  pkg/cidata/cidata.TEMPLATE.d/lima.env
  pkg/cidata/cidata.go
  pkg/cidata/template.go
  pkg/limayaml/limayaml.go
  pkg/vz/errors_darwin.go
  pkg/vz/rosetta_directory_share.go
  pkg/vz/rosseta_directory_share_arm64.go
  pkg/vz/vm_darwin.go
Labels: platform/ARM, component/vz

#1195 mount virtiofs directory only if mountType matches
  pkg/vz/vm_darwin.go
Labels: component/vz

#1196 CI: release: use Xcode 14.1 to enable the macOS 13 SDK
  .github/workflows/release.yml
  .github/workflows/test.yml
  Makefile
Labels: area/ci

#1201 mv examples/disk.yaml hack/test-templates/test-misc.yaml
  .github/workflows/test.yml
  hack/test-example.sh
  hack/test-templates/test-misc.yaml
Labels: area/ci, kind/refactoring

#1194 opensuse-tumbleweed: JeOS -> Minimal-VM
  examples/experimental/opensuse-tumbleweed.yaml
Labels: guest/opensuse

#1207 vz: support `.[]networks.vzNAT` networking
  .github/workflows/test.yml
  docs/network.md
  docs/vmtype.md
  examples/experimental/vz.yaml
  examples/vmnet.yaml
  pkg/limayaml/limayaml.go
  pkg/limayaml/validate.go
  pkg/vz/vm_darwin.go
Labels: component/vmnet, component/vz

#1215 templates: update EL derivatives to 8.7/9.1; Arch Linux to 20221115.102717; Debian 11 to 20221108-1193; Ubuntu 22.04 to release-20221117; Ubuntu 22.10 to release-20221101; Alpine to 3.17.0
  examples/almalinux-8.yaml
  examples/almalinux-9.yaml
  examples/alpine.yaml
  examples/archlinux.yaml
  examples/buildkit.yaml
  examples/centos-stream-8.yaml
  examples/centos-stream-9.yaml
  examples/debian.yaml
  examples/default.yaml
  examples/docker-rootful.yaml
  examples/docker.yaml
  examples/experimental/9p.yaml
  examples/experimental/riscv64.yaml
  examples/faasd.yaml
  examples/k3s.yaml
  examples/k8s.yaml
  examples/oraclelinux-8.yaml
  examples/oraclelinux-9.yaml
  examples/rocky-8.yaml
  examples/rocky-9.yaml
  examples/ubuntu-lts.yaml
  examples/ubuntu.yaml
  examples/vmnet.yaml
Labels: guest/archlinux, guest/debian, guest/ubuntu, guest/alpine, guest/el8, guest/el9
