Repository lima-vm/lima, pull requests merged in 2022-02, with the labels that each got.

#619 nerdctl: update to v0.16.1 (Fixes several `nerdctl login` regressions)
  pkg/limayaml/defaults.go
Labels: component/nerdctl

#621 Add Japanese translation of README
  README.ja.md
  README.md
Labels: documentation

#628 fix for PR #621
  README.ja.md
Labels: documentation

#630 examples: Add AlmaLinux to Lima
  README.ja.md
  README.md
  examples/README.md
  examples/almalinux.yaml
Labels: guest/el8

#634 examples: split the examples to "Tier 1" and others
  .cirrus.yml
  examples/README.md
Labels: documentation, area/project

#635 examples: update {alpine,archlinux,debian,nomad}.yaml
  examples/alpine.yaml
  examples/archlinux.yaml
  examples/debian.yaml
  examples/nomad.yaml
Labels: guest/archlinux, guest/debian, guest/alpine

#639 README.md: add debugging guide for Rancher Desktop users
  README.md
Labels: documentation, kind/external

#644 podman: use connection instead of CONTAINER_HOST
  examples/podman.yaml
Labels: podman

#643 add cpuType for specify cpu
  pkg/limayaml/default.yaml
  pkg/limayaml/defaults.go
  pkg/limayaml/defaults_test.go
  pkg/limayaml/limayaml.go
  pkg/limayaml/validate.go
  pkg/qemu/qemu.go
  pkg/store/instance.go
Labels: component/qemu

#657 Cleanup default and override warning in `limactl edit`
  cmd/limactl/start.go
Labels: enhancement

#656 Make cpuType a map instead of a single value
  pkg/limayaml/default.yaml
  pkg/limayaml/defaults.go
  pkg/limayaml/defaults_test.go
  pkg/limayaml/limayaml.go
  pkg/limayaml/validate.go
  pkg/qemu/qemu.go
  pkg/store/instance.go
Labels: enhancement

#660 Add portForwards.guestIPMustBeZero property
  hack/test-port-forwarding.pl
  pkg/hostagent/port.go
  pkg/limayaml/default.yaml
  pkg/limayaml/defaults.go
  pkg/limayaml/limayaml.go
  pkg/limayaml/validate.go
Labels: enhancement

#650 Allow adding static names to hostresolver
  cmd/limactl/debug.go
  examples/docker.yaml
  pkg/cidata/cidata.TEMPLATE.d/boot/06-etc-hosts.sh
  pkg/hostagent/dns/dns.go
  pkg/hostagent/hostagent.go
  pkg/limayaml/default.yaml
  pkg/limayaml/defaults.go
  pkg/limayaml/defaults_test.go
  pkg/limayaml/limayaml.go
Labels: enhancement, impact/changelog, status/merge-right-before-release

#662 examples/{almalinux,rocky}.yaml: use Lima v0.8.3 cpuType
  examples/almalinux.yaml
  examples/rocky.yaml
Labels: guest/el8, status/merge-right-before-release

#670 Add Alpine to the macOS test matrix
  .github/workflows/test.yml
Labels: area/ci, guest/alpine

#673 Document ping doesn't work due to SLIRP
  README.md
Labels: documentation
