Repository lima-vm/lima, pull requests merged in 2022-09, with the labels that each got.

#1047 Update nerdctl (0.23.0), Arch Linux, Debian, Ubuntu, Alpine
  examples/alpine.yaml
  examples/archlinux.yaml
  examples/buildkit.yaml
  examples/debian.yaml
  examples/default.yaml
  examples/docker-rootful.yaml
  examples/docker.yaml
  examples/experimental/9p.yaml
  examples/experimental/riscv64.yaml
  examples/faasd.yaml
  examples/k3s.yaml
  examples/k8s.yaml
  examples/ubuntu.yaml
  examples/vmnet.yaml
  pkg/limayaml/defaults.go
Labels: guest/archlinux, guest/debian, guest/ubuntu, guest/alpine, component/nerdctl

#851 vmnet: Support socket_vmnet; deprecate vde_vmnet
  .github/workflows/test.yml
  README.md
  docs/network.md
  examples/default.yaml
  examples/vmnet.yaml
  hack/test-example.sh
  pkg/hostagent/hostagent.go
  pkg/limayaml/defaults.go
  pkg/limayaml/defaults_test.go
  pkg/limayaml/limayaml.go
  pkg/limayaml/validate.go
  pkg/networks/commands.go
  pkg/networks/commands_darwin_test.go
  pkg/networks/commands_test.go
  pkg/networks/config.go
  pkg/networks/networks.go
  pkg/networks/networks.yaml
  pkg/networks/reconcile/reconcile.go
  pkg/networks/sudoers.go
  pkg/networks/validate.go
  pkg/qemu/qemu.go
Labels: component/vmnet, impact/changelog, roadmap

#1061 README.md: Lima is now a CNCF Sandbox project
  README.md
Labels: area/project

#1064 README.md: #lima channel is now hosted on CNCF Slack
  .github/ISSUE_TEMPLATE/config.yml
  README.ja.md
  README.md
Labels: area/project

#1052 templates: add podman-rootful
  examples/README.md
  examples/podman-rootful.yaml
Labels: podman

#1067 pkg/limayaml: fix comments about the overriding order
  pkg/limayaml/defaults.go
Labels: documentation

#1066 refactor (no substantial code change)
  .github/workflows/test.yml
  .golangci.yml
  cmd/lima-guestagent/install_systemd_linux.go
  cmd/limactl/edit.go
  cmd/limactl/guessarg/guessarg.go
  cmd/limactl/info.go
  cmd/limactl/start.go
  cmd/limactl/validate.go
  pkg/cidata/cidata.go
  pkg/cidata/template.go
  pkg/editutil/editutil.go
  pkg/hostagent/dns/dns_test.go
  pkg/infoutil/infoutil.go
  pkg/ioutilx/ioutilx.go
  pkg/networks/commands.go
  pkg/networks/config.go
  pkg/networks/networks.go
  pkg/networks/reconcile/reconcile.go
  pkg/networks/sudoers.go
  pkg/networks/validate.go
  pkg/osutil/osutil_linux.go
  pkg/osutil/osutil_others.go
  pkg/osutil/osutil_windows.go
  pkg/osutil/user.go
  pkg/templatestore/templatestore.go
  pkg/textutil/textutil.go
Labels: kind/refactoring

#1071 Fix segfault (master regression 2022-09-26)
  cmd/limactl/start.go
Labels: priority/high

#1076 templates: update apptainer to 1.1.0
  examples/experimental/apptainer.yaml
Labels: platform/ARM, guest/el8
