Repository lima-vm/lima, pull requests merged in 2022-05, with the labels that each got.

#843 Unmount mount points under /tmp before moving to persistent volume
  pkg/cidata/cidata.TEMPLATE.d/boot/05-persistent-data-volume.sh
Labels: guest/alpine

#827 experimental support for riscv64
  Makefile
  docs/internal.md
  examples/README.md
  examples/experimental/riscv64.yaml
  pkg/limayaml/defaults.go
  pkg/limayaml/defaults_test.go
  pkg/limayaml/limayaml.go
  pkg/limayaml/validate.go
  pkg/qemu/qemu.go
  pkg/store/filenames/filenames.go
Labels: enhancement

#820 feat: look for firmware in $HOME/.local/share/qemu
  pkg/qemu/qemu.go
Labels: component/qemu

#836 Enable reverse forwarding of portForwards
  examples/default.yaml
  pkg/hostagent/hostagent.go
  pkg/hostagent/port_darwin.go
  pkg/hostagent/port_others.go
  pkg/limayaml/defaults_test.go
  pkg/limayaml/limayaml.go
  pkg/limayaml/validate.go
Labels: enhancement

#854 templates: update Fedora to 36
  examples/fedora.yaml
  examples/singularity.yaml
Labels: guest/fedora

#855 Add client wrappers for docker and podman, similar to nerdctl wrapper
  Makefile
  cmd/docker.lima
  cmd/podman.lima
Labels: enhancement, impact/changelog, docker, podman

#859 nerdctl: update to v0.20.0
  pkg/limayaml/defaults.go
Labels: component/nerdctl

#860 templates: update alpine, archlinux, almalinux (but skip updating rocky)
  examples/almalinux.yaml
  examples/alpine.yaml
  examples/archlinux.yaml
  examples/rocky.yaml
Labels: guest/archlinux, guest/alpine, guest/el8

#864 [alpine] Persist /root on data volume at /mnt/data/root
  pkg/cidata/cidata.TEMPLATE.d/boot/05-persistent-data-volume.sh
Labels: guest/alpine

#863 Set required Containerd env vars in model zshrc - fixes #862
  pkg/cidata/cidata.TEMPLATE.d/boot/20-rootless-base.sh
Labels: component/nerdctl
