Repository lima-vm/lima, pull requests merged in 2022-10, with the labels that each got.

#1098 examples: add note that EL8 distros do not work on M1 (EL9 works)
  examples/almalinux.yaml
  examples/centos-stream.yaml
  examples/oraclelinux.yaml
  examples/rocky.yaml
Labels: platform/ARM, guest/el8

#1116 CI: allow broken hyperlinks to https://xbarapp.com
  .github/workflows/test.yml
Labels: area/ci

#1118 Bump alpine-lime to 0.2.23 to include growpart
  examples/alpine.yaml
Labels: guest/alpine

#1110 9p: change the default `securityModel` from `mapped-xattr` to `none`
  docs/mount.md
  examples/default.yaml
  pkg/limayaml/defaults.go
Labels: impact/changelog, component/qemu/9p

#1120 templates: Promote EL9 from experimental
  examples/README.md
  examples/almalinux-8.yaml
  examples/almalinux-9.yaml
  examples/almalinux.yaml
  examples/centos-stream-8.yaml
  examples/centos-stream-9.yaml
  examples/centos-stream.yaml
  examples/oraclelinux-8.yaml
  examples/oraclelinux-9.yaml
  examples/oraclelinux.yaml
  examples/rocky-8.yaml
  examples/rocky-9.yaml
  examples/rocky.yaml
Labels: impact/changelog, guest/el8, guest/el9
