Repository lima-vm/lima, pull requests merged in 2022-12, with the labels that each got.

#1216 support for validating unknown fields
  pkg/limayaml/defaults.go
  pkg/reflectutil/reflectutil.go
  pkg/vz/vz_driver_darwin.go
Labels: component/vz

#1236 nerdctl: update to v1.1.0; templates: update Arch Linux, Debian, Ubuntu, CentOS Stream, Rocky Linux
  examples/almalinux-9.yaml
  examples/archlinux.yaml
  examples/buildkit.yaml
  examples/centos-stream-9.yaml
  examples/debian.yaml
  examples/default.yaml
  examples/docker-rootful.yaml
  examples/docker.yaml
  examples/experimental/9p.yaml
  examples/experimental/riscv64.yaml
  examples/faasd.yaml
  examples/k3s.yaml
  examples/k8s.yaml
  examples/rocky-8.yaml
  examples/rocky-9.yaml
  examples/ubuntu-lts.yaml
  examples/ubuntu.yaml
  examples/vmnet.yaml
  pkg/limayaml/defaults.go
Labels: guest/archlinux, guest/debian, guest/ubuntu, component/nerdctl, guest/el8, guest/el9

#1220 vmnet: support detecting Homebrew's socket_vmnet path
  docs/network.md
  examples/vmnet.yaml
  pkg/networks/config.go
  pkg/networks/networks.TEMPLATE.yaml
  pkg/networks/sudoers.go
  pkg/networks/validate.go
Labels: component/vmnet

#1237 docs: update
  README.ja.md
  README.md
  docs/deprecated.md
  docs/experimental.md
  docs/multi-arch.md
  docs/network.md
  docs/talks.md
  docs/vmtype.md
  examples/default.yaml
  examples/experimental/vz.yaml
  pkg/vz/rosetta_directory_share_arm64.go
Labels: documentation

#1239 docs: fix diagram path
  Makefile
Labels: documentation

#1240 website: set up https://lima-vm.io/
  website/README.md
  website/index.html
Labels: documentation

#1243 Check if growpart is installed before calling it
  pkg/cidata/cidata.TEMPLATE.d/boot/04-persistent-data-volume.sh
Labels: priority/high, guest/alpine, downstream/colima

#1244 templates: almalinux-9: fix 404
  examples/almalinux-9.yaml
Labels: guest/el9

#1257 templates: update Arch Linux to 20221215.111177 ; CI: remove `brew upgrade` for avoiding issue 1256
  .github/workflows/test.yml
  examples/archlinux.yaml
Labels: guest/archlinux, area/ci

#1262 limactl info: add `vmTypes []string`
  pkg/driverutil/driverutil.go
  pkg/infoutil/infoutil.go
  pkg/vz/vz_driver_darwin.go
  pkg/vz/vz_driver_others.go
Labels: component/qemu, component/vz

#1261 vz: remove spice
  pkg/vz/vm_darwin.go
Labels: component/vz

#1268 improve vm disk performance with VZDiskImageSynchronizationModeFsync
  pkg/vz/vm_darwin.go
Labels: component/vz

#1249 add inspect CLI option
  cmd/limactl/inspect.go
  cmd/limactl/list.go
  cmd/limactl/main.go
  pkg/store/instance.go
Labels: area/cli
