Repository lima-vm/lima, pull requests merged in 2022-07, with the labels that each got.

#938 Add partial support for cygwin terminal on windows
  cmd/limactl/main.go
  cmd/limactl/shell.go
  cmd/limactl/start.go
  pkg/downloader/downloader.go
Labels: platform/Windows

#942 templates: update Rocky Linux to 8.6.20220702.0
  examples/experimental/apptainer.yaml
  examples/rocky.yaml
Labels: guest/el8

#915 Fix test failures on windows, mostly paths
  pkg/cidata/template.go
  pkg/hostagent/dns/dns_test.go
  pkg/limayaml/defaults.go
  pkg/limayaml/validate.go
  pkg/networks/commands.go
  pkg/networks/commands_darwin_test.go
  pkg/networks/commands_test.go
Labels: platform/Windows

#929 Add more fallbacks for LimaUser uid/gid/home
  pkg/osutil/user.go
  pkg/osutil/user_test.go
Labels: platform/Windows

#943 Add artifacts for windows (x86_64) target
  Makefile
Labels: platform/Windows

#944 Add lima wrapper for windows without bash
  Makefile
  cmd/lima.bat
Labels: platform/Windows

#953 Use forward slash for iso9660.Create on windows
  pkg/iso9660util/iso9660util.go
Labels: platform/Windows

#959 templates: add experimental/rocky-9
  examples/README.md
  examples/experimental/almalinux-9.yaml
  examples/experimental/centos-stream-9.yaml
  examples/experimental/rocky-9.yaml
Labels: guest/el9

#963 templates: update archlinux, debian, ubuntu, centos-stream-9, apptainer, alpine; update nerdctl (0.22.0)
  examples/alpine.yaml
  examples/archlinux.yaml
  examples/buildkit.yaml
  examples/debian.yaml
  examples/default.yaml
  examples/docker.yaml
  examples/experimental/9p.yaml
  examples/experimental/apptainer.yaml
  examples/experimental/centos-stream-9.yaml
  examples/experimental/riscv64.yaml
  examples/faasd.yaml
  examples/k3s.yaml
  examples/k8s.yaml
  examples/ubuntu.yaml
  examples/vmnet.yaml
  pkg/limayaml/defaults.go
Labels: guest/archlinux, guest/debian, guest/ubuntu, guest/alpine, component/nerdctl, guest/el9

#968 SECURITY.md: move to lima-vm/.github repo
  Makefile
  SECURITY.md
Labels: documentation, area/project

#970 Add ROADMAP.md
  ROADMAP.md
Labels: documentation, area/project

#969 Add Lima KubeCon 22 EU talk to repo
  README.md
  docs/talks.md
Labels: documentation

#979 Avoid translating paths in MSYS2 shell wrapper
  cmd/lima
Labels: platform/Windows

#992 CI: upgrading test: set the old ver to 0.10.0
  .github/workflows/test.yml
Labels: area/ci

#999 Add github test for windows using wine
  .github/workflows/test.yml
Labels: area/ci, platform/Windows

#990 Document the default option for video.display
  examples/default.yaml
Labels: documentation, component/qemu

#1000 templates: add experimental/oraclelinux-9
  examples/README.md
  examples/experimental/oraclelinux-9.yaml
  pkg/cidata/cidata.TEMPLATE.d/boot/30-install-packages.sh
Labels: guest/el9
