Repository lima-vm/lima, pull requests merged in 2022-06, with the labels that each got.

#876 Use Fedora 36 to get podman 4
  examples/podman.yaml
Labels: guest/ubuntu, impact/changelog, guest/fedora, podman

#891 Check for /sbin/openrc-run instead of /sbin/openrc-init
  pkg/cidata/cidata.TEMPLATE.d/boot.sh
  pkg/cidata/cidata.TEMPLATE.d/boot/11-colorterm-environment.sh
  pkg/cidata/cidata.TEMPLATE.d/boot/25-guestagent-base.sh
Labels: guest/alpine

#894 Only use cpuType=host for OS with accel available
  pkg/limayaml/defaults.go
  pkg/limayaml/defaults_test.go
Labels: component/qemu

#899 examples: use the geo.mirror.pkgbuild.com mirror for Arch Linux
  examples/archlinux.yaml
Labels: guest/archlinux

#901 Add examples for CentOS Linux and CentOS Stream both
  examples/README.md
  examples/centos-stream.yaml
  examples/experimental/centos-stream-9.yaml
  pkg/cidata/cidata.TEMPLATE.d/boot/30-install-packages.sh
Labels: guest/el8, guest/el9

#904 templates: add experimental/almalinux-9
  examples/README.md
  examples/experimental/almalinux-9.yaml
Labels: guest/el9

#908 Force sync after moving persistent directories to data volume
  pkg/cidata/cidata.TEMPLATE.d/boot/05-persistent-data-volume.sh
Labels: guest/alpine

#910 templates: update Arch Linux to 20220615.61815 ; nerdctl: update to v0.21.0
  examples/alpine.yaml
  examples/archlinux.yaml
  pkg/limayaml/defaults.go
Labels: guest/archlinux, component/nerdctl

#900 Not all OS with -accel has -cpu host option
  pkg/limayaml/defaults.go
  pkg/limayaml/defaults_test.go
Labels: component/qemu

#913 Fallbacks to `-cpu max` on native arch platforms that have an accelerator but do not support `-cpu host`
  pkg/limayaml/defaults.go
  pkg/limayaml/defaults_test.go
Labels: component/qemu, platform/NetBSD

#926 Add exe extension to the limactl binary on windows
  Makefile
Labels: platform/Windows

#931 whpx: Don't use -cpu max, add kernel-irqchip=off
  pkg/limayaml/defaults.go
  pkg/limayaml/defaults_test.go
  pkg/qemu/qemu.go
Labels: platform/Windows
