Repository lima-vm/lima, pull requests merged in 2023-02, with the labels that each got.

#1266 Hide columns in the list command
  cmd/limactl/list.go
  pkg/store/instance.go
  pkg/store/instance_test.go
Labels: area/cli

#1348 CI: update Go (1.20)
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: area/ci

#1361 detectAESAcceleration: workaround for darwin/amd64
  pkg/sshutil/sshutil.go
Labels: platform/ARM

#1365 Fix vz crash with video configuration
  pkg/hostagent/hostagent.go
  pkg/limayaml/defaults.go
Labels: component/vz

#1355 feat: recognize Kubernetes NodePorts and LoadBalancer
  go.mod
  go.sum
  pkg/guestagent/guestagent_linux.go
  pkg/guestagent/kubernetesservice/kubernetesservice.go
  pkg/guestagent/kubernetesservice/kubernetesservice_test.go
Labels: kubernetes

#1359 Add builtin yq support to lima start command
  README.md
  cmd/limactl/start.go
  docs/experimental.md
  go.mod
  go.sum
  pkg/yqutil/yqutil.go
  pkg/yqutil/yqutil_test.go
Labels: enhancement, impact/changelog, area/cli

#1369 Bump alpine-lima from 0.2.26 → 0.2.27
  examples/alpine.yaml
Labels: guest/alpine

#1374 Bump k8s flannel version from 0.20.2 to 0.21.2
  examples/k8s.yaml
Labels: kubernetes

#1378 Document `rdctl shell` command for Rancher Desktop
  README.md
Labels: documentation, kind/external

#1384 k8s: Remove redundant crictl.yaml config line
  examples/k8s.yaml
Labels: kubernetes

#1388 update nerdctl (1.2.1) and templates
  examples/archlinux.yaml
  examples/buildkit.yaml
  examples/centos-stream-9.yaml
  examples/debian.yaml
  examples/default.yaml
  examples/docker-rootful.yaml
  examples/docker.yaml
  examples/experimental/9p.yaml
  examples/experimental/opensuse-tumbleweed.yaml
  examples/experimental/riscv64.yaml
  examples/faasd.yaml
  examples/k3s.yaml
  examples/k8s.yaml
  examples/rocky-8.yaml
  examples/rocky-9.yaml
  examples/ubuntu-lts.yaml
  examples/ubuntu.yaml
  examples/vmnet.yaml
  pkg/limayaml/defaults.go
Labels: guest/archlinux, guest/debian, guest/ubuntu, component/nerdctl, guest/el8, guest/el9
