Repository lima-vm/lima, pull requests merged in 2023-04, with the labels that each got.

#1447 defaults.yaml is actually default.yaml
  examples/default.yaml
Labels: documentation

#1460 Update nerdctl to 1.3.0
  pkg/limayaml/defaults.go
Labels: component/nerdctl

#1462 Revert "templates: opensuse-tumbleweed: remove aarch64 image due to 404"
  examples/experimental/opensuse-tumbleweed.yaml
Labels: platform/ARM, guest/opensuse

#1463 refactor: vz disk conversion
  pkg/qemu/imgutil/imgutil.go
  pkg/vz/disk.go
  pkg/vz/vm_darwin.go
Labels: component/vz

#1469 limactl: let `limactl edit non-existent-instance` fail
  cmd/limactl/edit.go
Labels: bug, area/cli

#1471 Setup apk cache on persistent volume
  pkg/cidata/cidata.TEMPLATE.d/boot/04-persistent-data-volume.sh
Labels: guest/alpine

#1450 Added OpenSUSE aarch64
  examples/opensuse.yaml
Labels: platform/ARM, guest/opensuse

#1479 Bump k8s flannel version from 0.21.2 to 0.21.4
  examples/k8s.yaml
Labels: kubernetes

#1480 templates: openSUSE: fall back to provo-mirror.opensuse.org
  examples/experimental/opensuse-tumbleweed.yaml
  examples/opensuse.yaml
Labels: guest/opensuse

#1486 nerdctl: update to v1.3.1
  pkg/limayaml/defaults.go
Labels: component/nerdctl

#1487 qemu: disable pdpe1gb on Intel Mac
  examples/default.yaml
  pkg/limayaml/defaults.go
  pkg/limayaml/defaults_test.go
  pkg/qemu/qemu.go
Labels: priority/high, component/qemu

#1494 Fix panic during stop in vz driver
  pkg/vz/vm_darwin.go
  pkg/vz/vz_driver_darwin.go
Labels: component/vz

#1497 vz: fix mu
  pkg/vz/vm_darwin.go
  pkg/vz/vz_driver_darwin.go
Labels: component/vz

#1498 templates: update Arch Linux, CentOS Stream, Ubuntu
  examples/archlinux.yaml
  examples/buildkit.yaml
  examples/centos-stream-8.yaml
  examples/centos-stream-9.yaml
  examples/default.yaml
  examples/docker-rootful.yaml
  examples/docker.yaml
  examples/experimental/9p.yaml
  examples/experimental/riscv64.yaml
  examples/faasd.yaml
  examples/k3s.yaml
  examples/k8s.yaml
  examples/ubuntu-lts.yaml
  examples/ubuntu.yaml
  examples/vmnet.yaml
Labels: guest/archlinux, guest/ubuntu, guest/el8, guest/el9

#1510 MAINTAINERS.md: use GHSA for reporting security issues
  MAINTAINERS.md
Labels: documentation, area/project
