Repository lima-vm/lima, pull requests merged in 2023-05, with the labels that each got.

#1525 Update vz to 3.0.6
  go.mod
  go.sum
Labels: component/vz

#1527 Add audio device to limayaml and qemu
  examples/default.yaml
  pkg/limayaml/defaults.go
  pkg/limayaml/defaults_test.go
  pkg/limayaml/limayaml.go
  pkg/qemu/qemu.go
Labels: component/qemu

#1532 Support audio device for vz driver
  examples/default.yaml
  pkg/vz/vm_darwin.go
  pkg/vz/vz_driver_darwin.go
Labels: component/vz

#1521 Include manpages for lima and limactl commands
  Makefile
  cmd/limactl/genman.go
  cmd/limactl/main.go
  go.mod
  go.sum
Labels: documentation

#1539 Check qemu version in hostagent so not too old
  pkg/qemu/qemu.go
  pkg/qemu/qemu_test.go
Labels: component/qemu

#1545 vz: validate required version before hostagent start
  pkg/vz/vz_driver_darwin.go
Labels: component/vz

#1547 go.mod: bump up go-qemu, tcpproxy, k8s.io, golang.org/x, etc.
  go.mod
  go.sum
  pkg/bicopy/bicopy.go
  pkg/editutil/editorcmd/editorcmd.go
  pkg/editutil/editutil.go
  pkg/hostagent/port_darwin.go
Labels: dependencies, go

#1548 CI: replace Wine with Windows
  .github/workflows/test.yml
Labels: area/test, platform/Windows

#1550 templates: update AlmaLinux and Rocky Linux to 9.2; update Ubuntu to 23.04; update CentOS Stream, Arch Linux, Debian
  README.md
  examples/almalinux-9.yaml
  examples/archlinux.yaml
  examples/buildkit.yaml
  examples/centos-stream-8.yaml
  examples/centos-stream-9.yaml
  examples/debian.yaml
  examples/default.yaml
  examples/docker-rootful.yaml
  examples/docker.yaml
  examples/experimental/9p.yaml
  examples/experimental/riscv64.yaml
  examples/faasd.yaml
  examples/k3s.yaml
  examples/k8s.yaml
  examples/rocky-9.yaml
  examples/ubuntu-lts.yaml
  examples/ubuntu.yaml
  examples/vmnet.yaml
Labels: guest/archlinux, guest/debian, guest/ubuntu, guest/el8, guest/el9

#1549 docs/talks.md: update
  docs/talks.md
Labels: documentation

#1543 Fix unstable vz driver network issue
  pkg/networks/usernet/UDPFileConn.go
  pkg/networks/usernet/gvproxy.go
  pkg/vz/vm_darwin.go
Labels: component/vz

#1559 nerdctl: update to v1.4.0
  pkg/limayaml/defaults.go
Labels: component/nerdctl

#1560 Bump alpine from 3.17 → 3.18
  examples/alpine.yaml
Labels: guest/alpine

#1564 Alpine 3.18 on VZ requires macOS 13.3+
  examples/alpine.yaml
Labels: documentation, guest/alpine

#1562 CI: add colima compatibility test
  .cirrus.yml
  hack/test-colima.sh
Labels: area/test, downstream/colima

#1576 vz: silence `Ignoring: vmType vz: [CPUType]` when the value is empty
  pkg/vz/vz_driver_darwin.go
Labels: component/vz

#1579 [examples/k8s.yaml] the url to get gpg key for kubernetes is moved
  examples/k8s.yaml
Labels: kubernetes

#1575 vz: fail early when arch is invalid
  pkg/limayaml/validate.go
  pkg/vz/vz_driver_darwin.go
Labels: component/vz

#1580 Bump alpine to 0.2.30 and fix Rosetta support
  examples/alpine.yaml
  pkg/cidata/cidata.TEMPLATE.d/boot/05-rosetta-volume.sh
Labels: guest/alpine, component/vz

#1588 vz: add a note about kernel v6.2 (used by Ubuntu 23.04, Fedora 38, etc.)
  docs/vmtype.md
  examples/experimental/vz.yaml
Labels: documentation, component/vz

#1589 vz: remove audio input
  pkg/vz/vm_darwin.go
Labels: component/vz

#1590 Support for adding user-v2 network by default
  pkg/networks/config.go
  pkg/networks/config_test.go
Labels: component/network/user-v2

#1591 templates: update CentOS Stream 8, CentOS Stream 9, and Rocky Linux
  examples/centos-stream-8.yaml
  examples/centos-stream-9.yaml
  examples/rocky-8.yaml
Labels: guest/el8, guest/el9

#1592 Remove the output directory from the manpages
  Makefile
  cmd/limactl/genman.go
Labels: documentation
