Repository lima-vm/lima, pull requests merged in 2023-07, with the labels that each got.

#1651 Add Podman Desktop to the list of Lima adopters
  README.md
Labels: documentation, podman

#1652 Add fallback for the centos-stream-8 image too
  examples/centos-stream-8.yaml
Labels: guest/el8

#1669 Move apptainer examples to ubuntu ppa
  examples/apptainer-rootful.yaml
  examples/apptainer.yaml
Labels: guest/ubuntu, guest/fedora

#1675 templates: update Arch Linux to 20230715.165098
  examples/archlinux.yaml
Labels: guest/archlinux

#1676 CI: mostly disable snapshot tests
  hack/test-example.sh
Labels: area/test

#1674 qemu, vz: connect virtio serial to `serialv.log`
  docs/internal.md
  pkg/qemu/qemu.go
  pkg/qemu/qemu_driver.go
  pkg/store/filenames/filenames.go
  pkg/vz/vm_darwin.go
  pkg/vz/vz_driver_darwin.go
Labels: component/qemu, component/vz

#1658 Update DNS set up script to use a dedicated chain
  pkg/cidata/cidata.TEMPLATE.d/boot/09-host-dns-setup.sh
Labels: component/dns

#1680 Add fallback for the almalinux images
  examples/almalinux-8.yaml
  examples/almalinux-9.yaml
Labels: guest/el8, guest/el9

#1468 limactl: add `--cpus`, `--memory`, `--mount-type`, `--vm-type`, ...
  cmd/limactl/edit.go
  cmd/limactl/editflags/editflags.go
  cmd/limactl/editflags/editflags_test.go
  cmd/limactl/start.go
  docs/experimental.md
  hack/test-templates.sh
  pkg/yqutil/yqutil.go
Labels: enhancement, impact/changelog, area/cli

#1684 Don't repeatedly download get.k3s.io
  examples/k3s.yaml
Labels: kubernetes

#1692 Avoid warning about prefix with vz driver
  pkg/vz/vz_driver_darwin.go
Labels: component/vz

#1650 Add example config to deploy kubernetes via RKE2
  examples/experimental/rke2.yaml
Labels: kubernetes

#1693 qemu: virtio-serial-pci: set max_ports=1
  pkg/qemu/qemu.go
Labels: component/qemu

#1694 CI: test `template://docker` (and promote `template://docker` to "Tier 1")
  .cirrus.yml
  examples/README.md
  hack/test-templates.sh
Labels: area/test, docker

#1696 `limactl (create|start|edit)`: add `--video=<bool>`
  cmd/limactl/editflags/editflags.go
  docs/experimental.md
  pkg/vz/vm_darwin.go
  pkg/vz/vz_driver_darwin.go
Labels: area/cli

#1695 vz: show progressbar during converting qcow2 to raw
  pkg/downloader/downloader.go
  pkg/nativeimgutil/nativeimgutil.go
  pkg/progressbar/progressbar.go
  pkg/vz/disk.go
Labels: component/vz

#1699 Fix usernet socket name too long
  pkg/networks/usernet/config.go
  pkg/networks/usernet/config_test.go
  pkg/vz/vm_darwin.go
Labels: component/network/user-v2

#1700 nerdctl: update to v1.5.0; templates: update Ubuntu, Debian, openSUSE, CentOS Stream, Oracle Linux
  examples/apptainer-rootful.yaml
  examples/apptainer.yaml
  examples/buildkit.yaml
  examples/centos-stream-8.yaml
  examples/centos-stream-9.yaml
  examples/debian-11.yaml
  examples/debian-12.yaml
  examples/default.yaml
  examples/docker-rootful.yaml
  examples/docker.yaml
  examples/experimental/9p.yaml
  examples/experimental/armv7l.yaml
  examples/experimental/opensuse-tumbleweed.yaml
  examples/experimental/riscv64.yaml
  examples/experimental/rke2.yaml
  examples/experimental/virtiofs-linux.yaml
  examples/faasd.yaml
  examples/k3s.yaml
  examples/k8s.yaml
  examples/nomad.yaml
  examples/opensuse.yaml
  examples/oraclelinux-8.yaml
  examples/oraclelinux-9.yaml
  examples/ubuntu-lts.yaml
  examples/ubuntu.yaml
  examples/vmnet.yaml
  pkg/limayaml/defaults.go
Labels: guest/debian, guest/ubuntu, component/nerdctl, guest/el8, guest/el9, guest/opensuse
