Repository lima-vm/lima, pull requests merged in 2023-01, with the labels that each got.

#1286 Add a warning that nerdctl.lima only works in rootless mode
  examples/default.yaml
Labels: documentation, component/nerdctl

#1279 support socket_vmnet for vz driver
  docs/network.md
  examples/vmnet.yaml
  pkg/vz/network_darwin.go
  pkg/vz/vm_darwin.go
  pkg/vz/vz_driver_darwin.go
Labels: component/vmnet, component/vz

#1289 Return NODATA for IPv6 AAAA question types
  pkg/hostagent/dns/dns.go
Labels: component/dns

#1294 Closes the responseWriter after serving the Answer
  pkg/hostagent/dns/dns.go
Labels: component/dns

#1296 docs: add README zh translation and fix some bad links
  README.ja.md
  README.md
  README.zh.md
Labels: documentation

#1295 limactl: remove `limactl inspect` (not a breaking change)
  cmd/limactl/inspect.go
  cmd/limactl/main.go
Labels: area/cli

#1310 feat: report error when running under rosetta
  cmd/limactl/main.go
  pkg/osutil/rosetta_darwin.go
  pkg/osutil/rosetta_others.go
Labels: platform/ARM

#1315 fix unclean stop for vz driver
  pkg/vz/vz_driver_darwin.go
Labels: component/vz

#1321 templates: update Arch Linux to 20230115.118990
  examples/archlinux.yaml
Labels: guest/archlinux

#1322 CI: hyperlink check: allow 403 https://api.github.com
  .github/workflows/test.yml
Labels: area/ci

#1325 Split show_ssh.go (no substantial code change)
  cmd/limactl/show_ssh.go
  pkg/sshutil/format.go
Labels: kind/refactoring

#1323 MAINTAINERS.md: add afbjorklund and balajiv113
  MAINTAINERS.md
Labels: area/project

#1331 CI: update socket_vmnet (1.1.1)
  .github/workflows/test.yml
Labels: area/ci

#1340 Hide download progress when running tests
  pkg/downloader/downloader.go
  pkg/downloader/downloader_test.go
Labels: area/ci

#1332 Fix QEMU issue on binding multiple disks in M1
  pkg/qemu/qemu.go
Labels: platform/ARM, component/qemu

#1326 Write `~/.lima/<INSTANCE>/ssh.config`
  README.md
  cmd/limactl/show_ssh.go
  docs/internal.md
  pkg/hostagent/hostagent.go
  pkg/store/filenames/filenames.go
  pkg/store/instance.go
Labels: area/cli

#1267 Add template functions for list/inspect message
  cmd/limactl/list.go
  pkg/store/instance.go
  pkg/textutil/textutil.go
  pkg/textutil/textutil_test.go
Labels: area/cli

#1320 Show cloud-init-output.log when "nerdctl info" fails
  hack/test-example.sh
Labels: area/ci
