Repository lima-vm/lima, pull requests merged in 2023-12, with the labels that each got.

#2063 nerdctl: update to v1.7.2, templates: update Arch Linux, CentOS Stream 8, 9, Debian 12, Ubuntu 22.04
  examples/apptainer-rootful.yaml
  examples/apptainer.yaml
  examples/archlinux.yaml
  examples/centos-stream-8.yaml
  examples/centos-stream-9.yaml
  examples/debian-12.yaml
  examples/docker-rootful.yaml
  examples/docker.yaml
  examples/experimental/rke2.yaml
  examples/experimental/u7s.yaml
  examples/faasd.yaml
  examples/k3s.yaml
  examples/k8s.yaml
  examples/ubuntu-lts.yaml
  pkg/limayaml/defaults.go
Labels: guest/archlinux, guest/debian, guest/ubuntu, component/nerdctl, guest/el8, guest/el9

#2065 Add lima-guestagent logging for Alpine
  pkg/cidata/cidata.TEMPLATE.d/boot/25-guestagent-base.sh
Labels: guest/alpine

#2066 dependabot: enable groups
  .github/dependabot.yml
Labels: easy-to-review

#2067 go.mod: fix format
  go.mod
Labels: easy-to-review

#2016 Enable gocritic linter and fix issues
  .golangci.yml
  cmd/limactl/gendoc.go
  pkg/cidata/cidata.go
  pkg/downloader/downloader.go
  pkg/executil/command.go
  pkg/guestagent/guestagent_linux.go
  pkg/guestagent/procnettcp/procnettcp_linux.go
  pkg/hostagent/hostagent.go
  pkg/hostagent/mount.go
  pkg/hostagent/port.go
  pkg/hostagent/port_darwin.go
  pkg/hostagent/port_others.go
  pkg/hostagent/port_windows.go
  pkg/httpclientutil/httpclientutil.go
  pkg/limayaml/defaults.go
  pkg/limayaml/defaults_test.go
  pkg/networks/commands.go
  pkg/networks/config.go
  pkg/networks/usernet/config.go
  pkg/networks/usernet/dnshosts/dnshosts_test.go
  pkg/networks/usernet/gvproxy_test.go
  pkg/qemu/entitlementutil/entitlementutil.go
  pkg/qemu/imgutil/imgutil.go
  pkg/qemu/qemu.go
  pkg/sshutil/sshutil.go
  pkg/store/disk.go
  pkg/textutil/textutil.go
  pkg/vz/vm_darwin.go
Labels: kind/refactoring

#2080 CI: increase timeout for golangci-lint
  .github/workflows/test.yml
Labels: area/test

#2061 qemu, aarch64: use EDK2 from "Firmware/edk2 20231213 patches" (needed for QEMU v8.2.0)
  examples/default.yaml
  pkg/limayaml/defaults.go
  pkg/limayaml/defaults_test.go
  pkg/limayaml/limayaml.go
  pkg/qemu/qemu.go
  pkg/store/filenames/filenames.go
  pkg/vz/vz_driver_darwin.go
  website/content/en/docs/dev/Internals/_index.md
Labels: platform/ARM, component/qemu

#2082 templates: update Arch Linux to 20231215.200192
  examples/archlinux.yaml
Labels: guest/archlinux

#2084 qemu: UEFI: fix warning `Unexpected result from downloader.Download()`
  pkg/qemu/qemu.go
Labels: component/qemu

#2085 README.md: use separate logo for a dark GitHub theme
  README.md
  website/static/images/logo-dark.svg
Labels: documentation

#2095 fix limactl shell k3s kubectl command failed
  examples/k3s.yaml
Labels: kubernetes

#2103 Bump k8s flannel version from 0.22.1 to 0.24.0
  examples/k8s.yaml
Labels: kubernetes

#2078 Move all usage of survey into an internal pkg
  cmd/limactl/edit.go
  cmd/limactl/start.go
  pkg/qemu/entitlementutil/entitlementutil.go
  pkg/uiutil/uiutil.go
Labels: kind/refactoring, area/cli
