Repository lima-vm/lima, pull requests merged in 2023-09, with the labels that each got.

#1626 Support for configurable network address for user-v2
  cmd/limactl/usernet.go
  examples/experimental/net-user-v2.yaml
  go.mod
  hack/test-templates.sh
  pkg/cidata/cidata.TEMPLATE.d/boot/09-host-dns-setup.sh
  pkg/cidata/cidata.go
  pkg/cidata/cidata_test.go
  pkg/hostagent/hostagent.go
  pkg/networks/config_test.go
  pkg/networks/const.go
  pkg/networks/networks.TEMPLATE.yaml
  pkg/networks/usernet/client.go
  pkg/networks/usernet/config.go
  pkg/networks/usernet/config_test.go
  pkg/networks/usernet/dnshosts/dnshosts.go
  pkg/networks/usernet/dnshosts/dnshosts_test.go
  pkg/networks/usernet/gvproxy.go
  pkg/networks/usernet/recoincile.go
  pkg/qemu/qemu_driver.go
  pkg/vz/vm_darwin.go
Labels: component/network/user-v2

#1773 CI: add `apt-get update` to fix 404 errors
  .github/workflows/test.yml
Labels: area/test

#1778 Support for generating cli reference with different output formats
  Makefile
  cmd/limactl/gendoc.go
  cmd/limactl/main.go
Labels: documentation, area/cli

#1769 Avoid warning about OS with vz driver
  pkg/vz/vz_driver_darwin.go
Labels: component/vz

#1791 Update Debian examples to the latest September builds
  examples/debian-11.yaml
  examples/debian-12.yaml
Labels: guest/debian

#1804 docs: Usage: remove scaring caution
  website/content/en/docs/Usage/_index.md
Labels: documentation

#1806 mv docs/internals.md https://lima-vm.io/docs/dev/internals/
  docs/internals.md
  website/content/en/docs/dev/Internals/_index.md
  website/content/en/docs/dev/_index.md
  website/static/images/internals/lima-sequence-diagram.png
  website/static/images/internals/lima-sequence-diagram.puml
Labels: documentation

#1802 README.md: simplify
  README.md
Labels: documentation

#1809 docs: templates: recommend the new CLI form
  examples/README.md
Labels: documentation

#1810 docs: installation: use tabpane
  website/content/en/docs/Installation/_index.md
Labels: documentation

#1813 docs: examples: update
  website/content/en/docs/Examples/_index.md
Labels: documentation

#1814 docs: faq: remove outdated comparison with Docker for Mac
  website/content/en/docs/faq/_index.md
Labels: documentation, docker

#1807 mv docs/{mount,multi-arch,network,vmtype}.md https://lima-vm.io/docs/config/
  Makefile
  README.md
  docs/mount.md
  docs/mutli-arch.md
  docs/network.md
  docs/vmtype.md
  website/content/en/docs/Config/Mount/_index.md
  website/content/en/docs/Config/Multi-arch/_index.md
  website/content/en/docs/Config/Network/_index.md
  website/content/en/docs/Config/VMType/_index.md
  website/content/en/docs/Config/_index.md
Labels: documentation

#1818 docs: remove old version info to improve readability
  website/content/en/docs/Config/Multi-arch/_index.md
  website/content/en/docs/Config/Network/_index.md
  website/content/en/docs/Usage/_index.md
Labels: documentation

#1819 typo
  docs/multi-arch.md
Labels: documentation

#1820 Bump Nerdctl to 1.6.0
  pkg/limayaml/defaults.go
Labels: component/nerdctl

#1822 typo
  website/content/en/docs/Installation/_index.md
Labels: documentation

#1811 limactl: deprecate `limactl show-ssh` (Use `ssh -F ...` instead)
  cmd/limactl/show_ssh.go
  docs/deprecated.md
  website/content/en/docs/Usage/_index.md
Labels: impact/changelog, area/cli

#1823 docs: config/vmtype: add flowchart to choose the best vmType
  website/content/en/docs/Config/VMType/_index.md
  website/hugo.toml
Labels: documentation, component/vz

#1808 mv docs/{deprecated,experimental}.md https://lima-vm.io/docs/releases/
  docs/deprecated.md
  docs/experimental.md
  website/content/en/docs/Releases/Deprecated/_index.md
  website/content/en/docs/Releases/Experimental/_index.md
  website/content/en/docs/Releases/_index.md
Labels: documentation

#1825 fix: windows directory path containing spaces
  pkg/sshutil/sshutil.go
  pkg/wsl2/lima-init.TEMPLATE
Labels: platform/Windows

#1828 fix: allow non-admin users to run limactl start
  pkg/windows/registry_windows.go
Labels: platform/Windows

#1830 Fix vm freeze for invalid leases in user-v2
  pkg/cidata/cidata.go
  pkg/networks/usernet/config.go
  pkg/networks/usernet/config_test.go
  pkg/networks/usernet/gvproxy.go
  pkg/vz/vm_darwin.go
Labels: component/network/user-v2

#1832 CI: add go-licenses
  .github/workflows/test.yml
Labels: area/test

#1835 fix: adding full Podman Desktop logo
  website/data/adoptors.yaml
  website/static/images/users/podman-desktop.svg
Labels: documentation, podman

#1836 docs/config: add more tabpanes
  website/content/en/docs/Config/Mount/_index.md
  website/content/en/docs/Config/Multi-arch/_index.md
  website/content/en/docs/Config/Network/_index.md
  website/content/en/docs/Config/VMType/_index.md
  website/content/en/docs/Config/_index.md
  website/content/en/docs/Usage/_index.md
  website/content/en/docs/faq/_index.md
Labels: documentation

#1837 docs/faq: add colima
  website/content/en/docs/faq/colima/_index.md
Labels: documentation, downstream/colima

#1842 removed links from website/layouts/partials/footer.html
  website/layouts/partials/footer.html
Labels: documentation

#1850 Relax "QEMU binary /Users/<USER>/.colima/_wrapper/<HASH>/bin/qemu-system-x86_64 is not properly signed"
  pkg/qemu/entitlementutil/entitlementutil.go
Labels: downstream/colima

#1852 limactl: move `--set`, `--network`, and `--video` out of experimental
  cmd/limactl/editflags/editflags.go
  website/content/en/docs/Releases/Experimental/_index.md
Labels: impact/changelog, area/cli

#1857 CI: remove hack/fix-qemu-signature.sh
  .github/workflows/test.yml
Labels: area/test, component/qemu

#1860 docs: Update Japanese translation of README.ja.md
  README.ja.md
Labels: documentation

#1863 fix: Windows ssh command quoting
  pkg/sshutil/sshutil.go
Labels: platform/Windows

#1865 limactl sudoers: remove bogus user-v2 entries
  pkg/networks/sudoers.go
Labels: component/network/user-v2

#1869 templates: update Ubuntu, Alpine, ArchLinux, CentOS Stream
  examples/alpine.yaml
  examples/apptainer-rootful.yaml
  examples/apptainer.yaml
  examples/archlinux.yaml
  examples/buildkit.yaml
  examples/centos-stream-8.yaml
  examples/centos-stream-9.yaml
  examples/default.yaml
  examples/docker-rootful.yaml
  examples/docker.yaml
  examples/experimental/9p.yaml
  examples/experimental/armv7l.yaml
  examples/experimental/riscv64.yaml
  examples/experimental/rke2.yaml
  examples/experimental/virtiofs-linux.yaml
  examples/experimental/vz.yaml
  examples/faasd.yaml
  examples/k3s.yaml
  examples/k8s.yaml
  examples/ubuntu-lts.yaml
  examples/ubuntu.yaml
  examples/vmnet.yaml
Labels: guest/archlinux, guest/ubuntu, guest/alpine, guest/el8, guest/el9

#1870 docs: socketfilterfw needs sudo
  website/content/en/docs/Config/Network/_index.md
  website/content/en/docs/faq/_index.md
Labels: documentation, component/network/vmnet
