Repository lima-vm/lima, pull requests merged in 2024-12, with the labels that each got.

#2894 Add `boot/00-check-rtc-and-wait-ntp.sh` to cidata
  pkg/cidata/cidata.TEMPLATE.d/boot/00-check-rtc-and-wait-ntp.sh
Labels: component/vz

#2966 nerdctl: update to v2.0.1
  pkg/limayaml/containerd.yaml
Labels: component/nerdctl

#2954 website: add a guide for running Lima on GHA
  website/content/en/docs/examples/gha.md
Labels: documentation

#2967 docs/examples/gha: verify GitHub Attestations
  website/content/en/docs/examples/gha.md
Labels: documentation

#2996 Bump the kubeadm config beta version
  templates/k8s.yaml
Labels: kubernetes

#2974 CI and docs: update socket_vmnet (1.2.0)
  .github/workflows/test.yml
  website/content/en/docs/config/network.md
Labels: documentation, component/network/vmnet

#2990 Make sure to install podman package from repo
  templates/podman-rootful.yaml
  templates/podman.yaml
Labels: podman

#2971 portfwd: Fix handling the last UDP message
  pkg/portfwd/client.go
Labels: area/portfwd

#3009 Move template locator and reader code into new limatmpl package
  cmd/limactl/edit.go
  cmd/limactl/guessarg/guessarg.go
  cmd/limactl/main.go
  cmd/limactl/start.go
  cmd/limactl/template.go
  cmd/limactl/validate.go
  pkg/limatmpl/locator.go
  pkg/store/dirnames/dirnames.go
Labels: kind/refactoring

#2985 Revamp GRPC Port forwarding tunnels to use existing proxy
  pkg/portfwd/client.go
  pkg/portfwdserver/server.go
Labels: area/portfwd

#2998 [limactl copy] change make logs quiet by default and adds a verbose flag to enable verbose log output
  cmd/limactl/copy.go
Labels: area/cli

#3058 docs/internals.md: fix a broken symlink
  docs/internals.md
Labels: documentation

#3056 template: opensuse: virtiofs is not supported
  templates/experimental/opensuse-tumbleweed.yaml
  templates/opensuse-leap.yaml
Labels: component/sshfs, guest/opensuse, component/vz

#3054 limactl shell: avoid silencing errors
  cmd/limactl/shell.go
Labels: area/cli

#3059 website: docs/installation: update
  website/content/en/docs/installation/_index.md
Labels: documentation

#3048 templates: archlinux: allow 9p again
  templates/archlinux.yaml
Labels: guest/archlinux, component/qemu/9p

#3044 qemu: avoid `Property 'host-arm-cpu.sme' not found`
  .codespellrc
  pkg/limayaml/defaults.go
  pkg/osutil/osutil_unix.go
  pkg/osutil/osutil_windows.go
Labels: platform/ARM, component/qemu

#3062 enable search box on website
  website/hugo.toml
Labels: documentation

#3061 add nestedVirtualization documentation to default.yaml
  templates/default.yaml
Labels: documentation, component/vz

#3047 templates: add centos-stream-10
  templates/README.md
  templates/centos-stream-10.yaml
Labels: guest/el10
