Repository lima-vm/lima, pull requests merged in 2024-09, with the labels that each got.

#2572 Add ls-lint to the list of linters
  Makefile
Labels: area/test

#2569 `limactl prune`: add `--keep-referred` option to keep objects that are referred by some instances or templates
  cmd/limactl/prune.go
  pkg/downloader/downloader.go
Labels: area/cli

#2557 limactl: run file manipulation subcommands under Rosetta
  cmd/limactl/main.go
Labels: platform/ARM, component/vz

#2612 Rename opensuse to opensuse-leap
  examples/README.md
  examples/opensuse-leap.yaml
  examples/opensuse.yaml
Labels: guest/opensuse

#2593 Improve `limactl edit`
  cmd/limactl/edit.go
  go.mod
  go.sum
  pkg/yqutil/yqutil.go
  pkg/yqutil/yqutil_test.go
Labels: area/cli

#2595 Run usernet process in background
  pkg/executil/opts_others.go
  pkg/executil/opts_windows.go
  pkg/instance/start.go
  pkg/networks/usernet/recoincile.go
Labels: component/network/user-v2

#2562 VZ: Support Kernel Image
  hack/inject-cmdline-to-template.sh
  pkg/downloader/downloader.go
  pkg/vz/disk.go
  pkg/vz/vm_darwin.go
Labels: component/vz

#2634 go.mod: replace inet.af/tcpproxy -> github.com/inetaf/tcpproxy
  go.mod
  go.sum
  pkg/vz/network_darwin.go
Labels: cherry-pick/v0.23

#2640 CI: Downgrade to qemu-8.2.1
  .github/workflows/test.yml
Labels: status/more-info-needed, area/test

#2632 Prefer additional network over user network
  pkg/cidata/cidata.TEMPLATE.d/network-config
Labels: component/network/user-v2

#2630 Update selinux label for rosetta from nfs_t to bin_t
  hack/test-selinux.sh
  pkg/cidata/cidata.TEMPLATE.d/boot/05-lima-mounts.sh
Labels: platform/ARM, guest/fedora, component/vz
