Repository lima-vm/lima, pull requests merged in 2024-06, with the labels that each got.

#2382 Bump Alpine ISO from 3.19 to 3.20
  examples/alpine.yaml
Labels: guest/alpine

#2381 templates: update Rocky Linux to 8.10 and 9.4
  examples/rocky-8.yaml
  examples/rocky-9.yaml
Labels: guest/el8, guest/el9

#2385 website: add guide for testing
  website/content/en/docs/Community/Contributing/_index.md
  website/content/en/docs/dev/Testing/_index.md
Labels: documentation, area/test

#2394 website: Governance: Committers must enable 2FA for their GitHub accounts
  website/content/en/docs/Community/Governance/_index.md
Labels: documentation

#2391 README.md: add OpenSSF best practices badge
  README.md
Labels: documentation

#2383 MAINTAINERS: invite Oleksandr Redko (alexandear) as a Reviewer
  website/content/en/docs/Community/Governance/_index.md
Labels: area/project

#2412 website: fix typo in filename
  website/content/en/_index.html
  website/data/adopters.yaml
  website/layouts/shortcodes/blocks/adopters.html
Labels: documentation

#2410 Handle missing /etc/environment file in boot
  pkg/cidata/cidata.TEMPLATE.d/boot/07-etc-environment.sh
Labels: guest/opensuse

#2425 Use dummy WSL distro instead of OpenSUSE
  .github/workflows/test.yml
Labels: area/test, platform/Windows

#2447 cidata: fix upgrading nerdctl
  pkg/cidata/cidata.TEMPLATE.d/boot/40-install-containerd.sh
Labels: component/nerdctl
