Repository lima-vm/lima, pull requests merged in 2024-07, with the labels that each got.

#2457 templates: remove centos-stream-8, deprecated/centos-7
  examples/README.md
  examples/centos-stream-8.yaml
  examples/deprecated/centos-7.yaml
Labels: guest/el8

#2461 pkg/store: split pkg/version/versionutil
  pkg/store/instance.go
  pkg/store/instance_test.go
  pkg/version/versionutil/versionutil.go
  pkg/version/versionutil/versionutil_test.go
Labels: kind/refactoring

#2460 boot/04-persistent-data-volume.sh: fix 9p cache options
  pkg/cidata/cidata.TEMPLATE.d/boot/04-persistent-data-volume.sh
Labels: guest/alpine, component/qemu/9p

#2364 Remove the embedded default user in alpine cloud
  pkg/cidata/cidata.TEMPLATE.d/boot/00-alpine-user-group.sh
Labels: guest/alpine

#2474 [Rosetta] Prioritize rosetta over `qemu-user-static` by creating `binfmt.d(5)` configuration
  pkg/cidata/cidata.TEMPLATE.d/boot/05-rosetta-volume.sh
  pkg/cidata/cidata.TEMPLATE.d/user-data
Labels: component/vz

#2486 Bump alpine-image 3.19.1 → 3.20.1
  examples/alpine-image.yaml
Labels: guest/alpine

#2488 Make sure /proc/sys/fs/binfmt_misc has been mounted (on Alpine)
  pkg/cidata/cidata.TEMPLATE.d/boot/05-rosetta-volume.sh
Labels: guest/alpine

#2502 test.yml: include `matrix.template` in the cache key.
  .github/workflows/test.yml
Labels: area/test

#2504 Refactor stop/delete logic into pkg/instance
  cmd/limactl/delete.go
  cmd/limactl/factory-reset.go
  cmd/limactl/stop.go
  pkg/instance/delete.go
  pkg/instance/stop.go
  pkg/stop/stop.go
Labels: kind/refactoring

#2505 Move pkg/start/* → pkg/instance
  cmd/limactl/edit.go
  cmd/limactl/start.go
  pkg/instance/ansible.go
  pkg/instance/ha_cmd_opts_others.go
  pkg/instance/ha_cmd_opts_windows.go
  pkg/instance/start.go
Labels: kind/refactoring

#2507 test.yml: upload `failure-logs` as an artifact if `test-templates.sh` fails and `failure-logs` exists.
  .github/actions/upload_failure_logs_if_exists/action.yml
  .github/workflows/test.yml
  hack/test-templates.sh
Labels: area/test

#2498 limayaml: add a `param` field for defining variables used to customize scripts and other elements within `lima.yaml`.
  examples/default.yaml
  pkg/hostagent/hostagent.go
  pkg/limayaml/defaults.go
  pkg/limayaml/defaults_test.go
  pkg/limayaml/limayaml.go
  pkg/limayaml/load.go
  pkg/limayaml/validate.go
  pkg/limayaml/validate_test.go
  pkg/store/instance.go
  pkg/vz/vz_driver_darwin.go
  pkg/wsl2/wsl_driver_windows.go
Labels: impact/changelog

#2516 test.yml: expand the use of `upload_failure_logs_if_exists`.
  .github/workflows/test.yml
  hack/test-templates.sh
  hack/test-upgrade.sh
Labels: area/test

#2521 `cidata`: modify `user-data` to mount rosetta before `systemd-binfmt.service` starts.
  pkg/cidata/cidata.TEMPLATE.d/user-data
Labels: platform/ARM, component/vz
