Repository lima-vm/lima, pull requests merged in 2024-03, with the labels that each got.

#2151 CLI flag to generate autostart files
  cmd/limactl/delete.go
  cmd/limactl/main.go
  cmd/limactl/start-at-login.go
  pkg/autostart/autostart.go
  pkg/autostart/autostart_test.go
  pkg/autostart/io.lima-vm.autostart.INSTANCE.plist
  pkg/autostart/lima-vm@INSTANCE.service
Labels: area/cli

#2236 alpine: demote from Tier 1 to Tier 2
  examples/README.md
Labels: documentation, guest/alpine

#2238 Bump alpine-lima image from 0.2.35 → 0.2.37
  examples/alpine.yaml
Labels: guest/alpine, cherry-pick/v0.20

#2234 alpine: avoid wiping out writable host mounts under /home, etc.
  .github/workflows/test.yml
  hack/test-port-forwarding.pl
  hack/test-templates.sh
  hack/test-templates/alpine-9p-writable.yaml
  hack/test-templates/test-misc.yaml
  pkg/cidata/cidata.TEMPLATE.d/boot/04-persistent-data-volume.sh
Labels: priority/high, guest/alpine, cherry-pick/v0.20

#2242 Unmount MNTPNT before escaping quotes/backslashes
  pkg/cidata/cidata.TEMPLATE.d/boot/04-persistent-data-volume.sh
Labels: guest/alpine, cherry-pick/v0.20

#1913 Support for inotify in mounted directories
  cmd/limactl/editflags/editflags.go
  examples/default.yaml
  go.mod
  go.sum
  pkg/guestagent/api/client/client.go
  pkg/guestagent/api/guestservice.pb.desc
  pkg/guestagent/api/guestservice.pb.go
  pkg/guestagent/api/guestservice.proto
  pkg/guestagent/api/guestservice_grpc.pb.go
  pkg/guestagent/api/server/server.go
  pkg/guestagent/guestagent.go
  pkg/guestagent/guestagent_linux.go
  pkg/hostagent/hostagent.go
  pkg/hostagent/inotify.go
  pkg/hostagent/inotify_darwin.go
  pkg/hostagent/inotify_linux.go
  pkg/hostagent/inotify_others.go
  pkg/httpclientutil/httpclientutil.go
  pkg/limayaml/defaults.go
  pkg/limayaml/defaults_test.go
  pkg/limayaml/limayaml.go
  pkg/limayaml/validate.go
  pkg/vz/vz_driver_darwin.go
  website/content/en/docs/Config/Mount/_index.md
  website/content/en/docs/Releases/Experimental/_index.md
Labels: impact/changelog

#2250 docs/config: fix broken links
  website/content/en/docs/Config/Mount/_index.md
  website/content/en/docs/Config/Multi-arch/_index.md
  website/content/en/docs/Config/Network/_index.md
  website/content/en/docs/Config/VMType/_index.md
Labels: documentation

#2248 templates: update Ubuntu, Arch Linux, CentOS Stream, Debian
  examples/apptainer-rootful.yaml
  examples/apptainer.yaml
  examples/archlinux.yaml
  examples/buildkit.yaml
  examples/centos-stream-8.yaml
  examples/centos-stream-9.yaml
  examples/debian-11.yaml
  examples/debian-12.yaml
  examples/default.yaml
  examples/docker-rootful.yaml
  examples/docker.yaml
  examples/experimental/9p.yaml
  examples/experimental/armv7l.yaml
  examples/experimental/riscv64.yaml
  examples/experimental/rke2.yaml
  examples/experimental/u7s.yaml
  examples/experimental/virtiofs-linux.yaml
  examples/experimental/vnc.yaml
  examples/faasd.yaml
  examples/k3s.yaml
  examples/k8s.yaml
  examples/ubuntu-lts.yaml
  examples/ubuntu.yaml
  examples/vmnet.yaml
Labels: guest/archlinux, guest/debian, guest/ubuntu, guest/el8, guest/el9

#2251 nerdctl: update to v1.7.5
  pkg/limayaml/defaults.go
Labels: component/nerdctl

#2258 CI: drop Go 1.20
  .github/workflows/test.yml
  website/netlify.toml
Labels: area/test
