Repository lima-vm/lima, pull requests merged in 2025-05, with the labels that each got.

#3483 nerdctl: update to v2.0.5
  pkg/limayaml/containerd.yaml
Labels: component/nerdctl

#3485 Add dirnames.TemplatesDir() function
  pkg/store/dirnames/dirnames.go
  pkg/store/filenames/filenames.go
  pkg/templatestore/templatestore.go
Labels: kind/refactoring

#3484 Set riscv64 cpu to max
  pkg/limayaml/defaults.go
Labels: component/qemu

#3487 qemu: tcg: use `max` by default
  pkg/limayaml/defaults.go
  pkg/qemu/qemu.go
  templates/_images/centos-stream-10.yaml
  templates/default.yaml
Labels: component/qemu

#3488 qemu: experimental support for PPC64LE
  Kconfig
  Makefile
  cmd/limactl/editflags/editflags.go
  config.mk
  hack/inject-cmdline-to-template.sh
  hack/update-template.sh
  pkg/limatmpl/locator.go
  pkg/limayaml/defaults.go
  pkg/limayaml/defaults_test.go
  pkg/limayaml/limayaml.go
  pkg/limayaml/validate.go
  pkg/qemu/qemu.go
  pkg/sshutil/sshutil.go
  templates/_images/almalinux-8.yaml
  templates/_images/almalinux-9.yaml
  templates/_images/centos-stream-10.yaml
  templates/_images/centos-stream-9.yaml
  templates/_images/debian-11.yaml
  templates/_images/debian-12.yaml
  templates/_images/rocky-9.yaml
  templates/_images/ubuntu-20.04.yaml
  templates/_images/ubuntu-22.04.yaml
  templates/_images/ubuntu-24.04.yaml
  templates/_images/ubuntu-24.10.yaml
  templates/_images/ubuntu-25.04.yaml
  templates/experimental/debian-sid.yaml
  website/content/en/docs/releases/experimental.md
Labels: component/qemu

#3377 Refactor: Decouple Qemu Internal from `pkg/instance`
  pkg/instance/start.go
  pkg/qemu/qemu_driver.go
Labels: component/qemu

#3084 templates: add almalinux-kitten-10
  hack/update-template-almalinux-kitten.sh
  hack/update-template.sh
  templates/README.md
  templates/_images/almalinux-kitten-10.yaml
  templates/almalinux-kitten-10.yaml
  templates/almalinux-kitten.yaml
Labels: guest/el10

#3505 website: add DragonFlyBSD
  website/content/en/docs/installation/_index.md
Labels: documentation

#3491 Clean up codes for QEMU < 7.0
  .github/workflows/test.yml
  pkg/qemu/qemu.go
  website/content/en/docs/config/vmtype.md
  website/content/en/docs/installation/_index.md
Labels: kind/refactoring, component/qemu

#3515 Move jsonschema validation into a utility dir
  cmd/limactl/genschema.go
  pkg/jsonschemautil/jsonschemautil.go
  pkg/jsonschemautil/jsonschemautil_test.go
  pkg/jsonschemautil/testdata/invalid.yaml
  pkg/jsonschemautil/testdata/schema.json
  pkg/jsonschemautil/testdata/valid.yaml
Labels: kind/refactoring

#3504 guestagent refactoring
  cmd/limactl/hostagent.go
  pkg/cidata/cidata.go
  pkg/hostagent/hostagent.go
  pkg/infoutil/infoutil.go
  pkg/instance/start.go
  pkg/usrlocalsharelima/usrlocalsharelima.go
Labels: kind/refactoring

#3523 decoupling imgutils from filenams
  cmd/limactl/disk.go
  pkg/nativeimgutil/nativeimgutil.go
  pkg/qemu/imgutil/imgutil.go
Labels: kind/refactoring

#3528 templates: oraclelinux-8: known to work on M1
  templates/_images/oraclelinux-8.yaml
Labels: platform/ARM, guest/el8

#3531 CI: set GOTOOLCHAIN=local to prevent auto update of Go
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: area/test

#3503 Makefile: split lima-additional-guestagents-*.tar.gz from lima-*.tar.gz
  .github/workflows/release.yml
  Makefile
  hack/validate-artifact.sh
  website/content/en/docs/installation/_index.md
  website/content/en/docs/installation/source.md
Labels: impact/changelog

#3537 vz: Intel Mac: warn if macOS < 15.5
  pkg/vz/vz_driver_darwin.go
  templates/_images/fedora-42.yaml
  templates/_images/ubuntu-25.04.yaml
Labels: component/vz, platform/x86_64

#3543 Always return an error when a requested instance is not found
  cmd/limactl/list.go
Labels: area/cli

#3556 Rename infoutil.GetInfo() to info.New()
  cmd/limactl/info.go
  pkg/limainfo/limainfo.go
Labels: kind/refactoring

#3557 fix(cidata): do not overwrite bash in alpine vm
  pkg/cidata/cidata.TEMPLATE.d/boot/01-alpine-ash-as-bash.sh
Labels: guest/alpine

#3560 nerdctl: update from v2.1.1 to v2.1.2
  pkg/limayaml/containerd.yaml
Labels: priority/high, component/nerdctl

#3539 feat: add resize disk guide
  website/content/en/docs/config/disk.md
Labels: documentation

#3566 Locate the limactl executable via os.Args[0] instead of os.Executable()
  pkg/usrlocalsharelima/usrlocalsharelima.go
Labels: area/homebrew

#3578 Move `identifierutil` → `instance/hostname` package
  pkg/cidata/cidata.go
  pkg/hostagent/hostagent.go
  pkg/identifierutil/identifierutil_test.go
  pkg/instance/hostname/hostname.go
  pkg/instance/hostname/hostname_test.go
  pkg/limayaml/defaults.go
  pkg/sshutil/format.go
  pkg/store/instance.go
Labels: kind/refactoring
