Repository lima-vm/lima, pull requests merged in 2025-08, with the labels that each got.

#3802 docs: add a placeholder for emeritus maintainers
  website/content/en/docs/community/governance.md
Labels: documentation

#3867 community: set up regular Zoom meetings
  website/content/en/docs/community/_index.md
Labels: documentation, area/project

#3863 limactl (create|start) --help: indent examples
  cmd/limactl/start.go
Labels: area/cli, easy-to-review

#3842 Add fallback for busybox hostname with wsl2
  pkg/store/instance_windows.go
Labels: platform/Windows

#3884 README.md: add meeting information
  README.md
Labels: documentation, easy-to-review

#3902 Display the error when the plugin command failed to run
  cmd/limactl/main.go
Labels: area/cli

#3915 `limactl restart`: add `--progress`
  cmd/limactl/restart.go
  pkg/instance/restart.go
Labels: area/cli

#3912 Document GitHub teams and repo access rules
  website/content/en/docs/community/governance.md
Labels: documentation, area/project

#3910 refactor: support external drivers for the recent changes
  cmd/limactl/clone.go
  cmd/limactl/edit.go
  cmd/limactl/prune.go
  cmd/limactl/start.go
  cmd/limactl/template.go
  pkg/cidata/cidata.TEMPLATE.d/boot/05-rosetta-volume.sh
  pkg/driver/driver.go
  pkg/driver/external/client/methods.go
  pkg/driver/external/driver.pb.go
  pkg/driver/external/driver.proto
  pkg/driver/external/driver_grpc.pb.go
  pkg/driver/external/server/methods.go
  pkg/driver/external/server/server.go
  pkg/driver/qemu/qemu_driver.go
  pkg/driver/vz/vz_driver_darwin.go
  pkg/driver/wsl2/wsl_driver_windows.go
  pkg/driverutil/instance.go
  pkg/driverutil/vm.go
  pkg/hostagent/hostagent.go
  pkg/instance/create.go
  pkg/instance/start.go
  pkg/limatype/lima_yaml.go
  pkg/limayaml/validate.go
  pkg/limayaml/validate_test.go
  pkg/registry/registry.go
  pkg/registry/registry_test.go
  pkg/store/store.go
Labels: gsoc/2025, area/vmdrivers

#3923 driver: remove AcceptConfig
  pkg/driver/driver.go
  pkg/driver/external/client/methods.go
  pkg/driver/external/server/server.go
  pkg/driver/qemu/qemu_driver.go
  pkg/driver/vz/vz_driver_darwin.go
  pkg/driver/wsl2/wsl_driver_windows.go
  pkg/driverutil/vm.go
  pkg/registry/registry_test.go
Labels: area/vmdrivers
