Repository lima-vm/lima, pull requests merged in 2025-02, with the labels that each got.

#3227 qemu: revert "Restrict pessimization of M4 arch to macOS 15.2"; upgrade Cortex-A72 to Cortex-A76
  pkg/limayaml/defaults.go
  templates/default.yaml
  website/content/en/docs/installation/_index.md
Labels: priority/high, platform/ARM, component/qemu

#3235 install-containerd.sh: check RefuseManualStart property of dbus
  pkg/cidata/cidata.TEMPLATE.d/boot/40-install-containerd.sh
Labels: component/nerdctl, guest/opensuse

#3233 WSL: Create symlink at /mnt/lima-cidata
  pkg/cidata/cidata.TEMPLATE.d/boot/02-wsl2-setup.sh
Labels: platform/Windows

#3239 Splitted https://lima-vm.io/docs/config/network/ to multiple pages
  website/content/en/docs/config/network/_index.md
  website/content/en/docs/config/network/user-v2.md
  website/content/en/docs/config/network/user.md
  website/content/en/docs/config/network/vmnet.md
Labels: documentation

#3259 docs/config/network: follow-up
  website/content/en/docs/config/network/_index.md
  website/content/en/docs/config/network/user-v2.md
  website/content/en/docs/config/network/user.md
  website/content/en/docs/config/network/vmnet.md
Labels: documentation

#3254 Use SSHAddress for SSH forwarding in QEMU
  pkg/qemu/qemu.go
  pkg/qemu/qemu_driver.go
Labels: component/qemu, platform/Windows

#3261 Add optional loading of UEFI firmware via -bios parameter in QEMU
  pkg/qemu/qemu.go
  pkg/store/filenames/filenames.go
  website/content/en/docs/config/environment-variables.md
Labels: component/qemu, platform/Windows

#3285 build(deps): bump golang.org/x/crypto from 0.33.0 to 0.35.0
  go.mod
  go.sum
Labels: dependencies, github_actions
