Repository lima-vm/lima, pull requests merged in 2025-03, with the labels that each got.

#3280 Enable Integration tests in Windows CI
  .github/workflows/test.yml
  hack/common.inc.sh
  hack/test-mount-home.sh
  hack/test-port-forwarding.pl
  hack/test-templates.sh
  pkg/osutil/user.go
Labels: platform/Windows

#3072 Assemble templates using the new `base` setting
  .github/workflows/test.yml
  cmd/limactl/start.go
  cmd/limactl/template.go
  hack/cache-common-inc.sh
  hack/test-port-forwarding.pl
  hack/test-templates.sh
  hack/test-templates/test-misc.yaml
  pkg/limatmpl/abs.go
  pkg/limatmpl/abs_test.go
  pkg/limatmpl/embed.go
  pkg/limatmpl/embed_test.go
  pkg/limatmpl/locator.go
  pkg/limatmpl/template.go
  pkg/limayaml/limayaml.go
  pkg/limayaml/marshal.go
  pkg/limayaml/validate.go
  pkg/limayaml/validate_test.go
  pkg/store/filenames/filenames.go
  pkg/templatestore/templatestore.go
  templates/default.yaml
  website/content/en/docs/releases/experimental.md
Labels: impact/changelog

#3314 docs/examples/gha: use lima-actions
  website/content/en/docs/community/subprojects.md
  website/content/en/docs/examples/gha.md
Labels: documentation

#3328 templates: add experimental/debian-sid
  templates/README.md
  templates/experimental/debian-sid.yaml
Labels: guest/debian

#3344 vz: included Kernel and Initrd as known feilds
  pkg/vz/vz_driver_darwin.go
Labels: component/vz

#3351 Update WSL2 tempate and enable systemd tests on Windows
  hack/test-templates.sh
  templates/experimental/wsl2.yaml
Labels: platform/Windows

#3180 limactl disk: Do not use qemu-img for raw disks
  cmd/limactl/disk.go
  pkg/nativeimgutil/nativeimgutil.go
Labels: component/vz

#3347 Support setting extra entries for PATH env variable on Windows hosts
  cmd/limactl/main.go
  pkg/qemu/qemu.go
  website/content/en/docs/config/environment-variables.md
Labels: platform/Windows

#3343 separated binary installation
  website/content/en/docs/installation/_index.md
  website/content/en/docs/installation/source.md
Labels: documentation

#3304 Improve Subsystem paths handling on Windows hosts
  cmd/limactl/shell.go
  pkg/ioutilx/ioutilx.go
  pkg/osutil/user.go
Labels: platform/Windows

#3352 Start QEMU binary as a background process
  hack/test-templates.sh
  pkg/qemu/qemu_driver.go
Labels: component/qemu

#3353 Fix mount support in QEMU on Windows hosts
  pkg/hostagent/mount.go
  pkg/limayaml/defaults.go
  pkg/limayaml/defaults_test.go
Labels: component/qemu, platform/Windows

#3357 Enable port forwarding tests for WSL2
  .github/workflows/test.yml
  hack/test-port-forwarding.pl
  hack/test-templates.sh
Labels: area/test, platform/Windows, area/portfwd

#3372 update nerdctl (2.0.4) and templates
  pkg/limayaml/containerd.yaml
  templates/apptainer-rootful.yaml
  templates/apptainer.yaml
  templates/archlinux.yaml
  templates/buildkit.yaml
  templates/centos-stream-10.yaml
  templates/centos-stream-9.yaml
  templates/debian-11.yaml
  templates/debian-12.yaml
  templates/default.yaml
  templates/docker-rootful.yaml
  templates/docker.yaml
  templates/experimental/alsa.yaml
  templates/experimental/rke2.yaml
  templates/experimental/u7s.yaml
  templates/experimental/vnc.yaml
  templates/faasd.yaml
  templates/k3s.yaml
  templates/k8s.yaml
  templates/ubuntu-20.04.yaml
  templates/ubuntu-22.04.yaml
  templates/ubuntu-24.04.yaml
  templates/ubuntu-24.10.yaml
Labels: component/nerdctl, cherry-pick/done, cherry-pick/v1.0

#3373 [release/1.0] cherry-picks for v1.0.7 (nerdctl v2.0.4 etc.)
  go.mod
  go.sum
  pkg/limayaml/containerd.yaml
  pkg/qemu/qemu.go
  templates/apptainer-rootful.yaml
  templates/apptainer.yaml
  templates/archlinux.yaml
  templates/buildkit.yaml
  templates/centos-stream-10.yaml
  templates/centos-stream-9.yaml
  templates/debian-11.yaml
  templates/debian-12.yaml
  templates/default.yaml
  templates/docker-rootful.yaml
  templates/docker.yaml
  templates/experimental/alsa.yaml
  templates/experimental/rke2.yaml
  templates/experimental/u7s.yaml
  templates/experimental/vnc.yaml
  templates/faasd.yaml
  templates/k3s.yaml
  templates/k8s.yaml
  templates/ubuntu-20.04.yaml
  templates/ubuntu-22.04.yaml
  templates/ubuntu-24.04.yaml
  templates/ubuntu-24.10.yaml
  website/content/en/docs/config/environment-variables.md
Labels: component/nerdctl
