Repository lima-vm/lima, pull requests merged in 2025-09, with the labels that each got.

#3938 Use errors.As() instead of type assertions
  cmd/limactl/main.go
  pkg/downloader/downloader.go
  pkg/networks/usernet/udpfileconn.go
Labels: kind/refactoring

#3941 `docker{,-rootful}.yaml`: Enable the containerd image store by default
  templates/docker-rootful.yaml
  templates/docker.yaml
Labels: impact/changelog, docker

#3858 feature: use Rosetta AOT Caching with CDI
  pkg/cidata/cidata.TEMPLATE.d/boot/40-install-containerd.sh
  pkg/driver/vz/boot/05-rosetta-volume.sh
  pkg/driver/vz/rosetta_directory_share_arm64.go
  templates/docker-rootful.yaml
  templates/docker.yaml
  website/content/en/docs/config/multi-arch.md
Labels: expert, impact/changelog, docker, component/vz

#3942 vzNAT: fix regression
  pkg/driver/qemu/qemu_driver.go
  pkg/driver/vz/vz_driver_darwin.go
  pkg/limayaml/validate.go
Labels: priority/high, component/network/vzNAT

#3951 templates: default: remove /tmp/lima
  pkg/yqutil/yqutil_test.go
  templates/_default/mounts.yaml
  templates/default.yaml
  website/content/en/docs/config/_index.md
  website/content/en/docs/examples/_index.md
Labels: impact/changelog

#3947 editflags: add `--mount-only` flag
  cmd/limactl/editflags/editflags.go
  cmd/limactl/editflags/editflags_test.go
Labels: area/cli

#3961 driverutil: allow external driver stderr
  pkg/driverutil/vm.go
Labels: area/vmdrivers

#3972 docs: split long pages, fix minor errors, etc.
  website/content/en/docs/config/environment-variables.md
  website/content/en/docs/config/multi-arch.md
  website/content/en/docs/config/plugin/_index.md
  website/content/en/docs/config/plugin/cli.md
  website/content/en/docs/config/plugin/vm.md
  website/content/en/docs/config/port.md
  website/content/en/docs/config/vmtype.md
  website/content/en/docs/config/vmtype/_index.md
  website/content/en/docs/config/vmtype/qemu.md
  website/content/en/docs/config/vmtype/vz.md
  website/content/en/docs/config/vmtype/wsl2.md
  website/content/en/docs/examples/_index.md
  website/content/en/docs/installation/_index.md
  website/content/en/docs/reference/_index.md
  website/content/en/docs/talks/_index.md
  website/content/en/docs/usage/_index.md
Labels: documentation

#3956 make check-generated: check reproducibility of *.pb.go too
  Makefile
  hack/gogenerate/protoc.sh
  pkg/driver/external/driver.pb.go
  pkg/driver/external/driver_grpc.pb.go
  pkg/driver/external/gen.go
  pkg/guestagent/api/gen.go
  pkg/guestagent/api/guestservice.pb.go
  pkg/guestagent/api/guestservice_grpc.pb.go
Labels: priority/high, area/test, cherry-pick/v1.2

#3861 Remove VMType check from the lima-init boot script
  pkg/cidata/cidata.TEMPLATE.d/lima.env
  pkg/cidata/cidata.go
  pkg/cidata/template.go
  pkg/driver/driver.go
  pkg/driver/wsl2/boot/02-no-cloud-init-setup.sh
  pkg/driver/wsl2/wsl_driver_windows.go
  pkg/hostagent/hostagent.go
Labels: area/vmdrivers

#3992 Don't read VMOpts.VZ struct from cidata directly
  pkg/cidata/cidata.go
  pkg/driver/driver.go
  pkg/driver/vz/vz_driver_darwin.go
  pkg/hostagent/hostagent.go
  pkg/limayaml/defaults.go
Labels: component/vz

#4077 Add port monitoring test script
  hack/bats/extras/port-monitor.bats
Labels: area/test, area/portfwd

#4111 template:k8s: fix "toml: table io.containerd.grpc.v1.cri already exists"
  pkg/cidata/cidata.TEMPLATE.d/boot/40-install-containerd.sh
  templates/k8s.yaml
Labels: priority/high, kubernetes

#4109 CI: test UDP port forwarding
  hack/test-templates.sh
Labels: area/test, area/portfwd

#4095 `limactl shell`, `ssh.config`: Remove `ControlMaster`, `ControlPath`, and `ControlPersist` options on Windows
  cmd/limactl/shell.go
  pkg/hostagent/hostagent.go
  pkg/sshutil/sshutil.go
Labels: platform/Windows

#4102 feat(guestagent/sockets): replace /proc/net parsing with NETLINK_INET_DIAG
  go.mod
  go.sum
  pkg/guestagent/guestagent_linux.go
  pkg/guestagent/procnettcp/fuzz_test.go
  pkg/guestagent/procnettcp/procnettcp.go
  pkg/guestagent/procnettcp/procnettcp_linux.go
  pkg/guestagent/procnettcp/procnettcp_test.go
  pkg/guestagent/sockets/sockets.go
  pkg/guestagent/sockets/sockets_linux.go
  pkg/guestagent/sockets/sockets_linux_test.go
Labels: area/portfwd
