Repository lima-vm/lima, pull requests merged in 2025-04, with the labels that each got.

#3323 cmd: add support for restarting a running instance
  cmd/limactl/main.go
  cmd/limactl/restart.go
  cmd/limactl/stop.go
  pkg/instance/restart.go
  pkg/instance/stop.go
Labels: area/cli

#3413 CI: fix the commit hash of golangci-lint-action
  .github/workflows/test.yml
Labels: area/test, easy-to-review

#3393 Bind QEMU GA socket only in virtio mode
  pkg/qemu/qemu.go
  pkg/qemu/qemu_driver.go
Labels: component/qemu

#3419 Fix slow image pull caused by delayed DNS response
  pkg/hostagent/dns/dns.go
Labels: component/dns

#3378 Unify Lima user home inside guest for all platforms
  pkg/limayaml/defaults_test.go
  pkg/osutil/user.go
Labels: platform/Windows

#3434 templates: add fedora-42
  .github/workflows/test.yml
  templates/README.md
  templates/fedora-41.yaml
  templates/fedora-42.yaml
  templates/fedora.yaml
Labels: guest/fedora, cherry-pick/v1.0

#3431 Enable gRPC port forwarder by default again
  .github/workflows/test.yml
  pkg/hostagent/hostagent.go
  website/content/en/docs/config/environment-variables.md
  website/content/en/docs/config/port.md
  website/content/en/docs/releases/deprecated.md
Labels: impact/changelog, area/portfwd

#3441 oraclelinux: fix virtiofs support
  pkg/cidata/cidata.TEMPLATE.d/boot/30-install-packages.sh
Labels: guest/el8, guest/el9, component/vz

#3445 templates: add ubuntu-25.04
  .github/workflows/test.yml
  templates/ubuntu-25.04.yaml
Labels: guest/ubuntu

#3454 templates: add linuxbrew
  templates/README.md
  templates/linuxbrew.yaml
Labels: area/homebrew

#3466 Fix `nativeimgutil_test.go` on Windows with QEMU installed
  pkg/nativeimgutil/nativeimgutil_test.go
Labels: component/qemu, platform/Windows

#3439 Support: limactl disk import command
  cmd/limactl/disk.go
Labels: area/cli
