Repository lima-vm/lima, pull requests merged in 2025-10, with the labels that each got.

#4117 guestagent: reuse netlink connections
  cmd/lima-guestagent/daemon_linux.go
  pkg/guestagent/guestagent.go
  pkg/guestagent/guestagent_linux.go
  pkg/guestagent/sockets/sockets_linux.go
  pkg/guestagent/sockets/sockets_linux_test.go
Labels: area/portfwd

#4131 docs: fix links, add more GHA examples
  pkg/driver/qemu/qemu.go
  website/content/en/docs/examples/gha.md
  website/content/en/docs/faq/_index.md
Labels: documentation, easy-to-review

#4130 docs: add examples/vscode
  website/content/en/docs/examples/vscode.md
  website/static/images/vscode-remote-explorer.png
Labels: documentation

#4121 docs: add examples for AI agents
  website/content/en/docs/config/ai/inside/_index.md
  website/content/en/docs/examples/ai.md
Labels: documentation

#4143 pkg/driver/qemu: Avoid calling `checkBinarySignature()` from `FillConfig()`.
  pkg/driver/qemu/qemu_driver.go
Labels: component/qemu

#4076 Use driver feature instead of checking the name
  pkg/driver/driver.go
  pkg/driver/wsl2/wsl_driver_windows.go
  pkg/driverutil/instance.go
  pkg/hostagent/hostagent.go
Labels: area/vmdrivers

#4146 hack/test-templates.sh: remove `--cpus 1 --memory 1`
  .github/workflows/test.yml
  hack/test-templates.sh
Labels: area/test

#4147 CI: split the BATS tests into a separate job
  .github/workflows/test.yml
Labels: area/test

#4151 docs: mention BATS tests
  website/content/en/docs/dev/testing.md
Labels: documentation, area/test

#4134 Implement custom `github:` URL scheme in Go
  hack/bats/tests/url-github.bats
  pkg/limatmpl/github.go
  pkg/limatmpl/locator.go
Labels: impact/changelog

#4156 hack/test-port-forwarding.pl: add reporting "failed to listen tcp"
  hack/test-port-forwarding.pl
Labels: area/test, area/portfwd

#4163 docs: update port benchmark results
  website/content/en/docs/config/port.md
Labels: documentation, easy-to-review, area/portfwd

#4161 hack: remove unused fix-qemu-signature.sh
  hack/fix-qemu-signature.sh
Labels: component/qemu, easy-to-review

#4157 docs: dev/testing: fix a typo
  website/content/en/docs/dev/testing.md
Labels: documentation, easy-to-review

#4158 make generate: improve reproducibility
  hack/gogenerate/protoc.sh
  pkg/driver/external/driver.pb.go
  pkg/driver/external/driver_grpc.pb.go
  pkg/guestagent/api/guestservice.pb.go
  pkg/guestagent/api/guestservice_grpc.pb.go
Labels: easy-to-review
