Repository lima-vm/lima, pull requests merged in 2025-06, with the labels that each got.

#3631 fix(edk2): update candidates path on Arch Linux
  pkg/qemu/qemu.go
Labels: component/qemu

#3475 Add QEMU on Windows to CI
  .github/workflows/test.yml
  hack/test-templates.sh
Labels: component/qemu, platform/Windows

#3647 editflags: add `--mount-none`
  cmd/limactl/editflags/editflags.go
Labels: enhancement, area/cli

#3643 templates: default: use Ubuntu 25.04, Fedora 42
  .github/workflows/test.yml
  hack/test-templates.sh
  pkg/limayaml/defaults.go
  templates/README.md
  templates/_images/fedora.yaml
  templates/_images/ubuntu.yaml
  templates/default.yaml
  templates/fedora.yaml
  templates/podman-rootful.yaml
  templates/podman.yaml
  templates/ubuntu.yaml
  website/content/en/docs/config/mount.md
Labels: priority/high

#3664 docs: remove unnecessary references to macOS
  .github/workflows/release.yml
  README.md
  website/content/en/docs/config/disk.md
Labels: documentation, easy-to-review
