Repository lima-vm/lima, pull requests merged in 2025-01, with the labels that each got.

#3083 Use sync.OnceValue to implement hasSMEDarwin()
  pkg/limayaml/defaults.go
Labels: kind/refactoring

#3064 website: remove sidebar search box and enhance the one in the top navigation bar
  website/assets/scss/_variables_project.scss
  website/hugo.toml
Labels: documentation

#3085 website: add simple makefile for testing locally
  website/Makefile
Labels: documentation

#3082 Move k8s image pull to a separate step
  templates/k8s.yaml
Labels: kubernetes

#3098 redirect user to release page on GitHub
  website/hugo.toml
Labels: documentation

#3097 Disable the epel-cisco-openh264 repository
  pkg/cidata/cidata.TEMPLATE.d/boot/30-install-packages.sh
Labels: guest/el9

#3096 Only install fuse-sshfs from epel
  pkg/cidata/cidata.TEMPLATE.d/boot/30-install-packages.sh
Labels: component/sshfs, guest/el9

#3120 fix inconsistent error in limactl create command when instance name and template is specified
  cmd/limactl/start.go
Labels: area/cli

#3123 cidata: Use mac address as dhcpd identifier
  pkg/cidata/cidata.TEMPLATE.d/network-config
Labels: component/network/vmnet

#3065 Disable AVX-512 support for macOS Intel host
  pkg/limayaml/defaults.go
Labels: guest/el10, platform/x86_64

#3134 update nerdctl, templates, and comments
  pkg/limayaml/containerd.yaml
  templates/alpine.yaml
  templates/apptainer-rootful.yaml
  templates/apptainer.yaml
  templates/archlinux.yaml
  templates/buildkit.yaml
  templates/centos-stream-10.yaml
  templates/centos-stream-9.yaml
  templates/debian-12.yaml
  templates/default.yaml
  templates/docker-rootful.yaml
  templates/docker.yaml
  templates/experimental/alsa.yaml
  templates/experimental/rke2.yaml
  templates/experimental/u7s.yaml
  templates/experimental/vnc.yaml
  templates/faasd.yaml
  templates/k3s.yaml
  templates/k8s.yaml
  templates/ubuntu-20.04.yaml
  templates/ubuntu-22.04.yaml
  templates/ubuntu-24.04.yaml
  templates/ubuntu-24.10.yaml
Labels: component/nerdctl, guest/el10

#3165 website gha.md: job env variable sets LIMA_VERSION
  website/content/en/docs/examples/gha.md
Labels: documentation
