Repository lima-vm/lima, pull requests merged in 2025-07, with the labels that each got.

#3677 Implement `limactl network (list|create|delete)`
  cmd/limactl/completion.go
  cmd/limactl/disk.go
  cmd/limactl/main.go
  cmd/limactl/network.go
  pkg/networks/networks.go
Labels: area/cli, component/network/user-v2

#3702 CI: unify Windows runners to `windows-2025`
  .github/workflows/test.yml
Labels: area/test, platform/Windows

#3710 editflags: fix shell completion for containerd
  cmd/limactl/editflags/editflags.go
Labels: easy-to-review

#3709 De-deprecate LIMA_SSH_PORT_FORWARDER
  pkg/hostagent/hostagent.go
  website/content/en/docs/config/environment-variables.md
  website/content/en/docs/releases/deprecated.md
Labels: area/portfwd

#3692 Feature: Registry for drivers and expose driver info in CLI
  cmd/limactl/start.go
  pkg/driverutil/driverutil.go
  pkg/limainfo/limainfo.go
  pkg/registry/registry.go
  pkg/usrlocalsharelima/usrlocalsharelima.go
Labels: gsoc/2025

#3693 Feature: Internal driver plugin system
  cmd/limactl/main_darwin.go
  cmd/limactl/main_qemu.go
  cmd/limactl/main_windows.go
  pkg/driver/driver.go
  pkg/driver/qemu/qemu_driver.go
  pkg/driver/qemu/register.go
  pkg/driver/vz/errors_darwin.go
  pkg/driver/vz/register.go
  pkg/driver/vz/vz_driver_darwin.go
  pkg/driver/vz/vz_driver_others.go
  pkg/driver/wsl2/errors_windows.go
  pkg/driver/wsl2/register.go
  pkg/driver/wsl2/wsl_driver_others.go
  pkg/driver/wsl2/wsl_driver_windows.go
  pkg/driverutil/instance.go
  pkg/hostagent/hostagent.go
  pkg/instance/create.go
  pkg/instance/delete.go
  pkg/instance/start.go
  pkg/registry/registry.go
  pkg/snapshot/snapshot.go
Labels: gsoc/2025

#3694 Feature: External driver plugin system and update Makefile
  Makefile
  cmd/lima-driver-qemu/main.go
  cmd/lima-driver-vz/main_darwin.go
  cmd/lima-driver-wsl2/main_windows.go
  cmd/limactl/main.go
  pkg/driver/external/client/client.go
  pkg/driver/external/client/methods.go
  pkg/driver/external/driver.pb.go
  pkg/driver/external/driver.proto
  pkg/driver/external/driver_grpc.pb.go
  pkg/driver/external/server/methods.go
  pkg/driver/external/server/server.go
  pkg/driverutil/instance.go
  pkg/instance/start.go
  pkg/networks/usernet/client.go
  pkg/registry/registry.go
  pkg/store/filenames/filenames.go
  pkg/store/instance.go
Labels: gsoc/2025

#3737 Fix proto style issues; enable protolint
  .github/workflows/test.yml
  .protolint.yaml
  Makefile
  pkg/driver/external/driver.proto
  pkg/guestagent/api/guestservice.pb.desc
  pkg/guestagent/api/guestservice.pb.go
  pkg/guestagent/api/guestservice.proto
  pkg/guestagent/guestagent_linux.go
  pkg/hostagent/port.go
  pkg/portfwd/forward.go
Labels: area/test

#3724 portfwd: create separate gRPC streams for each UDP client
  pkg/portfwd/client.go
Labels: area/portfwd, cherry-pick/v1.2

#3742 qemuimgutil: fix "Failed to get \"write\" lock" error
  pkg/instance/start.go
  pkg/instance/start_unix.go
  pkg/instance/start_windows.go
  pkg/qemuimgutil/qemuimgutil.go
Labels: cherry-pick/v1.2
